//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Attachment {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Attachment() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QA.Localization.Attachment", typeof(Attachment).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Attachments.
        /// </summary>
        public static string AddAttachments {
            get {
                return ResourceManager.GetString("AddAttachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment Added successfully.
        /// </summary>
        public static string AttachAddedSuccess {
            get {
                return ResourceManager.GetString("AttachAddedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach File.
        /// </summary>
        public static string Attachment_AddAttached {
            get {
                return ResourceManager.GetString("Attachment_AddAttached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to attachment.
        /// </summary>
        public static string attachmentName {
            get {
                return ResourceManager.GetString("attachmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please provide a valid sample code.
        /// </summary>
        public static string avalid_Sample_Code {
            get {
                return ResourceManager.GetString("avalid_Sample_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please provide a valid sample-test name.
        /// </summary>
        public static string avalid_Sample_TestName {
            get {
                return ResourceManager.GetString("avalid_Sample_TestName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CR ID: .
        /// </summary>
        public static string CRID {
            get {
                return ResourceManager.GetString("CRID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kindly select file to be attached.
        /// </summary>
        public static string MissingAttachFile {
            get {
                return ResourceManager.GetString("MissingAttachFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Upload Error.
        /// </summary>
        public static string MissingAttachFile_Header {
            get {
                return ResourceManager.GetString("MissingAttachFile_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Sample test.
        /// </summary>
        public static string provide_SampleTest {
            get {
                return ResourceManager.GetString("provide_SampleTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please select sample-test result.
        /// </summary>
        public static string provide_SampleTest_Result {
            get {
                return ResourceManager.GetString("provide_SampleTest_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Sample test Category.
        /// </summary>
        public static string provide_SampleTestCategory {
            get {
                return ResourceManager.GetString("provide_SampleTestCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample code: .
        /// </summary>
        public static string sampleCode {
            get {
                return ResourceManager.GetString("sampleCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sample code field length between 1 - 20 characters.
        /// </summary>
        public static string SampleCode_length_validation {
            get {
                return ResourceManager.GetString("SampleCode_length_validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sample result: .
        /// </summary>
        public static string sampleResult {
            get {
                return ResourceManager.GetString("sampleResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted.
        /// </summary>
        public static string SampleResult_Accepted {
            get {
                return ResourceManager.GetString("SampleResult_Accepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected.
        /// </summary>
        public static string SampleResult_Rejected {
            get {
                return ResourceManager.GetString("SampleResult_Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - Select - .
        /// </summary>
        public static string SampleResult_Select {
            get {
                return ResourceManager.GetString("SampleResult_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample test category: *.
        /// </summary>
        public static string sampleTestCategoryID {
            get {
                return ResourceManager.GetString("sampleTestCategoryID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample test: *.
        /// </summary>
        public static string sampleTestID {
            get {
                return ResourceManager.GetString("sampleTestID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sample-test name.
        /// </summary>
        public static string sampleTestName {
            get {
                return ResourceManager.GetString("sampleTestName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sample-test name field length between 1 - 50 characters.
        /// </summary>
        public static string SampleTestname_length_validation {
            get {
                return ResourceManager.GetString("SampleTestname_length_validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Attachmnent file.
        /// </summary>
        public static string SelectFileValidation {
            get {
                return ResourceManager.GetString("SelectFileValidation", resourceCulture);
            }
        }
    }
}
