//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CheckListFlow_Sequence {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CheckListFlow_Sequence() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QA.Localization.CheckListFlow_Sequence", typeof(CheckListFlow_Sequence).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Provide a valid Description.
        /// </summary>
        public static string avalid_Description {
            get {
                return ResourceManager.GetString("avalid_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Provide a valid Sequence name.
        /// </summary>
        public static string avalid_Name {
            get {
                return ResourceManager.GetString("avalid_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Sequence.
        /// </summary>
        public static string CreateSequence {
            get {
                return ResourceManager.GetString("CreateSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to description: *.
        /// </summary>
        public static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description field length between 5 - 200 characters.
        /// </summary>
        public static string Description_length_validation {
            get {
                return ResourceManager.GetString("Description_length_validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to description: .
        /// </summary>
        public static string description_Search {
            get {
                return ResourceManager.GetString("description_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to description.
        /// </summary>
        public static string description_ViewSearch {
            get {
                return ResourceManager.GetString("description_ViewSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checklist should contain at least 1 maker and 1 checker.
        /// </summary>
        public static string Error_MakerCantBeChecker {
            get {
                return ResourceManager.GetString("Error_MakerCantBeChecker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checklist Authorizer should be determined.
        /// </summary>
        public static string Error_MissedAuthorizer {
            get {
                return ResourceManager.GetString("Error_MissedAuthorizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checklist Maker should be determined.
        /// </summary>
        public static string Error_MissedMaker {
            get {
                return ResourceManager.GetString("Error_MissedMaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QA Lab. Max days should be determined.
        /// </summary>
        public static string Error_QALabMaxDays_NotInput {
            get {
                return ResourceManager.GetString("Error_QALabMaxDays_NotInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Superior Max days should be determined.
        /// </summary>
        public static string Error_RepSuperMaxDays_NotInput {
            get {
                return ResourceManager.GetString("Error_RepSuperMaxDays_NotInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Super Eng. Max days should be determined.
        /// </summary>
        public static string Error_SuperEngMaxDays_NotInput {
            get {
                return ResourceManager.GetString("Error_SuperEngMaxDays_NotInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technician Max days should be determined.
        /// </summary>
        public static string Error_TechnicianMaxDays_NotInput {
            get {
                return ResourceManager.GetString("Error_TechnicianMaxDays_NotInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max period range 0 - 10 days.
        /// </summary>
        public static string MaxPeriod_Range {
            get {
                return ResourceManager.GetString("MaxPeriod_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence Name: *.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence name field length between 5 - 100 characters.
        /// </summary>
        public static string Name_length_validation {
            get {
                return ResourceManager.GetString("Name_length_validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence Name: .
        /// </summary>
        public static string name_Search {
            get {
                return ResourceManager.GetString("name_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence Name.
        /// </summary>
        public static string name_ViewSearch {
            get {
                return ResourceManager.GetString("name_ViewSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence name already exist !.
        /// </summary>
        public static string NameAlreadyExist {
            get {
                return ResourceManager.GetString("NameAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Period:.
        /// </summary>
        public static string qALab_maxDays {
            get {
                return ResourceManager.GetString("qALab_maxDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QA-Lab user: .
        /// </summary>
        public static string qALabID {
            get {
                return ResourceManager.GetString("qALabID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Representitive-Supervisor: .
        /// </summary>
        public static string representitiveSuperID {
            get {
                return ResourceManager.GetString("representitiveSuperID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Period:.
        /// </summary>
        public static string repSuper_maxDays {
            get {
                return ResourceManager.GetString("repSuper_maxDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Sequences.
        /// </summary>
        public static string SearchSequences {
            get {
                return ResourceManager.GetString("SearchSequences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence Added Successfully.
        /// </summary>
        public static string SequenceAddedSuccessfully {
            get {
                return ResourceManager.GetString("SequenceAddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence Details.
        /// </summary>
        public static string SequenceDetails {
            get {
                return ResourceManager.GetString("SequenceDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence Not Available in database !.
        /// </summary>
        public static string SequenceID_Not_Available_inDB {
            get {
                return ResourceManager.GetString("SequenceID_Not_Available_inDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence Updated Successfully.
        /// </summary>
        public static string SequenceUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("SequenceUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Period:.
        /// </summary>
        public static string superEng_maxDays {
            get {
                return ResourceManager.GetString("superEng_maxDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to supervisor-Eng: .
        /// </summary>
        public static string supervisorEngID {
            get {
                return ResourceManager.GetString("supervisorEngID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Period: .
        /// </summary>
        public static string technician_maxDays {
            get {
                return ResourceManager.GetString("technician_maxDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technician: .
        /// </summary>
        public static string technicianID {
            get {
                return ResourceManager.GetString("technicianID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Sequence.
        /// </summary>
        public static string UpdateSequence {
            get {
                return ResourceManager.GetString("UpdateSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QA-Lab.
        /// </summary>
        public static string ViewTable_QALab {
            get {
                return ResourceManager.GetString("ViewTable_QALab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QA. Max-days.
        /// </summary>
        public static string ViewTable_QALab_MD {
            get {
                return ResourceManager.GetString("ViewTable_QALab_MD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوكيل.
        /// </summary>
        public static string ViewTable_RepSuper {
            get {
                return ResourceManager.GetString("ViewTable_RepSuper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوكيل. Max-days.
        /// </summary>
        public static string ViewTable_RepSuper_MD {
            get {
                return ResourceManager.GetString("ViewTable_RepSuper_MD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supervisor Eng. .
        /// </summary>
        public static string ViewTable_SuperEng {
            get {
                return ResourceManager.GetString("ViewTable_SuperEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Super Max-days.
        /// </summary>
        public static string ViewTable_SuperEng_MD {
            get {
                return ResourceManager.GetString("ViewTable_SuperEng_MD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technician.
        /// </summary>
        public static string ViewTable_Technician {
            get {
                return ResourceManager.GetString("ViewTable_Technician", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tech. Max-days.
        /// </summary>
        public static string ViewTable_Technician_MD {
            get {
                return ResourceManager.GetString("ViewTable_Technician_MD", resourceCulture);
            }
        }
    }
}
