//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CheckListFlow_Master {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CheckListFlow_Master() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QA.Localization.CheckListFlow_Master", typeof(CheckListFlow_Master).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string Accept_CLF {
            get {
                return ResourceManager.GetString("Accept_CLF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Provide Comment.
        /// </summary>
        public static string Avalid_Comment {
            get {
                return ResourceManager.GetString("Avalid_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a valid Check-list Party.
        /// </summary>
        public static string avalid_Party {
            get {
                return ResourceManager.GetString("avalid_Party", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheker.
        /// </summary>
        public static string checklist_Checker {
            get {
                return ResourceManager.GetString("checklist_Checker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maker.
        /// </summary>
        public static string checklist_Maker {
            get {
                return ResourceManager.GetString("checklist_Maker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check-list retrieve Error.
        /// </summary>
        public static string checkListDataRetrieveError {
            get {
                return ResourceManager.GetString("checkListDataRetrieveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check-list flow Added successfully.
        /// </summary>
        public static string CLF_AddedSuccessfully {
            get {
                return ResourceManager.GetString("CLF_AddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maker Added successfully.
        /// </summary>
        public static string CLF_Maker_AddedSuccessfully {
            get {
                return ResourceManager.GetString("CLF_Maker_AddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string CLF_Maker_Comments_Header {
            get {
                return ResourceManager.GetString("CLF_Maker_Comments_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        public static string CLF_Maker_IsAvailable_Available {
            get {
                return ResourceManager.GetString("CLF_Maker_IsAvailable_Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        public static string CLF_Maker_IsAvailable_Header {
            get {
                return ResourceManager.GetString("CLF_Maker_IsAvailable_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not-Available.
        /// </summary>
        public static string CLF_Maker_IsAvailable_NotAvailable {
            get {
                return ResourceManager.GetString("CLF_Maker_IsAvailable_NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - Select - .
        /// </summary>
        public static string CLF_Maker_IsAvailable_Select {
            get {
                return ResourceManager.GetString("CLF_Maker_IsAvailable_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check-List Flow.
        /// </summary>
        public static string CLFlow_Create_ScreenTitle {
            get {
                return ResourceManager.GetString("CLFlow_Create_ScreenTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status: .
        /// </summary>
        public static string CLFlowStatus {
            get {
                return ResourceManager.GetString("CLFlowStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check-List: *.
        /// </summary>
        public static string cLID {
            get {
                return ResourceManager.GetString("cLID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closure date: .
        /// </summary>
        public static string closurenDate {
            get {
                return ResourceManager.GetString("closurenDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check-List For: .
        /// </summary>
        public static string CLParty {
            get {
                return ResourceManager.GetString("CLParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check-List Sequence: *.
        /// </summary>
        public static string cLSequenceID {
            get {
                return ResourceManager.GetString("cLSequenceID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment field length between 2 - 250 characters.
        /// </summary>
        public static string Comment_length_validation {
            get {
                return ResourceManager.GetString("Comment_length_validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Check-List flow.
        /// </summary>
        public static string Create_CLF {
            get {
                return ResourceManager.GetString("Create_CLF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checklist should contain at least 1 maker and 1 checker.
        /// </summary>
        public static string Error_MakerCantBeChecker {
            get {
                return ResourceManager.GetString("Error_MakerCantBeChecker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checklist Authorizer should be determined.
        /// </summary>
        public static string Error_MissedAuthorizer {
            get {
                return ResourceManager.GetString("Error_MissedAuthorizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checklist Maker should be determined.
        /// </summary>
        public static string Error_MissedMaker {
            get {
                return ResourceManager.GetString("Error_MissedMaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QA Lab. Max days should be determined.
        /// </summary>
        public static string Error_QALabMaxDays_NotInput {
            get {
                return ResourceManager.GetString("Error_QALabMaxDays_NotInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Superior Max days should be determined.
        /// </summary>
        public static string Error_RepSuperMaxDays_NotInput {
            get {
                return ResourceManager.GetString("Error_RepSuperMaxDays_NotInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Super Eng. Max days should be determined.
        /// </summary>
        public static string Error_SuperEngMaxDays_NotInput {
            get {
                return ResourceManager.GetString("Error_SuperEngMaxDays_NotInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technician Max days should be determined.
        /// </summary>
        public static string Error_TechnicianMaxDays_NotInput {
            get {
                return ResourceManager.GetString("Error_TechnicianMaxDays_NotInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flow Details.
        /// </summary>
        public static string Flow_Details {
            get {
                return ResourceManager.GetString("Flow_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max period range 0 - 10 days.
        /// </summary>
        public static string MaxPeriod_Range {
            get {
                return ResourceManager.GetString("MaxPeriod_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party name field length between 5 - 100 characters.
        /// </summary>
        public static string Party_length_validation {
            get {
                return ResourceManager.GetString("Party_length_validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Check-lists.
        /// </summary>
        public static string Pending_Checklists {
            get {
                return ResourceManager.GetString("Pending_Checklists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select.
        /// </summary>
        public static string Provide_Available_Status {
            get {
                return ResourceManager.GetString("Provide_Available_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Check-list .
        /// </summary>
        public static string provide_avalid_CLID {
            get {
                return ResourceManager.GetString("provide_avalid_CLID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Check-List Sequence.
        /// </summary>
        public static string provide_avalid_cLSequence {
            get {
                return ResourceManager.GetString("provide_avalid_cLSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Period:.
        /// </summary>
        public static string qALab_maxDays {
            get {
                return ResourceManager.GetString("qALab_maxDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QA-Lab user: .
        /// </summary>
        public static string qALabID {
            get {
                return ResourceManager.GetString("qALabID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Date: .
        /// </summary>
        public static string registrationDate {
            get {
                return ResourceManager.GetString("registrationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejecet.
        /// </summary>
        public static string Rejecet_CLF {
            get {
                return ResourceManager.GetString("Rejecet_CLF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Representitive-Supervisor: .
        /// </summary>
        public static string representitiveSuperID {
            get {
                return ResourceManager.GetString("representitiveSuperID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Period:.
        /// </summary>
        public static string repSuper_maxDays {
            get {
                return ResourceManager.GetString("repSuper_maxDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Period:.
        /// </summary>
        public static string superEng_maxDays {
            get {
                return ResourceManager.GetString("superEng_maxDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to supervisor-Eng: .
        /// </summary>
        public static string supervisorEngID {
            get {
                return ResourceManager.GetString("supervisorEngID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Period: .
        /// </summary>
        public static string technician_maxDays {
            get {
                return ResourceManager.GetString("technician_maxDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technician: .
        /// </summary>
        public static string technicianID {
            get {
                return ResourceManager.GetString("technicianID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Check-List flow.
        /// </summary>
        public static string Update_CLF {
            get {
                return ResourceManager.GetString("Update_CLF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Pending Check-Lists.
        /// </summary>
        public static string Vew_Pending {
            get {
                return ResourceManager.GetString("Vew_Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Data retrieved successfully.
        /// </summary>
        public static string ViewData_RetrievedSuccess {
            get {
                return ResourceManager.GetString("ViewData_RetrievedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checker.
        /// </summary>
        public static string ViewTable_Action_Checker {
            get {
                return ResourceManager.GetString("ViewTable_Action_Checker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maker.
        /// </summary>
        public static string ViewTable_Action_Maker {
            get {
                return ResourceManager.GetString("ViewTable_Action_Maker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NA.
        /// </summary>
        public static string ViewTable_Action_NA {
            get {
                return ResourceManager.GetString("ViewTable_Action_NA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment.
        /// </summary>
        public static string ViewTable_Attachment {
            get {
                return ResourceManager.GetString("ViewTable_Attachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checklist.
        /// </summary>
        public static string ViewTable_CheckList {
            get {
                return ResourceManager.GetString("ViewTable_CheckList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check-list For.
        /// </summary>
        public static string ViewTable_CLParty {
            get {
                return ResourceManager.GetString("ViewTable_CLParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string ViewTable_Download {
            get {
                return ResourceManager.GetString("ViewTable_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NA.
        /// </summary>
        public static string ViewTable_Download_NotAvailable {
            get {
                return ResourceManager.GetString("ViewTable_Download_NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QA-Lab.
        /// </summary>
        public static string ViewTable_QALab {
            get {
                return ResourceManager.GetString("ViewTable_QALab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QA. Max-days.
        /// </summary>
        public static string ViewTable_QALab_MD {
            get {
                return ResourceManager.GetString("ViewTable_QALab_MD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration date.
        /// </summary>
        public static string ViewTable_RegistrationDate {
            get {
                return ResourceManager.GetString("ViewTable_RegistrationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوكيل.
        /// </summary>
        public static string ViewTable_RepSuper {
            get {
                return ResourceManager.GetString("ViewTable_RepSuper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوكيل. Max-days.
        /// </summary>
        public static string ViewTable_RepSuper_MD {
            get {
                return ResourceManager.GetString("ViewTable_RepSuper_MD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string ViewTable_Status {
            get {
                return ResourceManager.GetString("ViewTable_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supervisor Eng. .
        /// </summary>
        public static string ViewTable_SuperEng {
            get {
                return ResourceManager.GetString("ViewTable_SuperEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Super Max-days.
        /// </summary>
        public static string ViewTable_SuperEng_MD {
            get {
                return ResourceManager.GetString("ViewTable_SuperEng_MD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technician.
        /// </summary>
        public static string ViewTable_Technician {
            get {
                return ResourceManager.GetString("ViewTable_Technician", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tech. Max-days.
        /// </summary>
        public static string ViewTable_Technician_MD {
            get {
                return ResourceManager.GetString("ViewTable_Technician_MD", resourceCulture);
            }
        }
    }
}
