//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CheckLists {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CheckLists() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QA.Localization.CheckLists", typeof(CheckLists).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check-list Added Successfully.
        /// </summary>
        public static string CheckListsAddedSuccessfully {
            get {
                return ResourceManager.GetString("CheckListsAddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check-list Details.
        /// </summary>
        public static string CheckListsDetails {
            get {
                return ResourceManager.GetString("CheckListsDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check-list Not Available in Database !.
        /// </summary>
        public static string CheckListsID_Not_Available_inDB {
            get {
                return ResourceManager.GetString("CheckListsID_Not_Available_inDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Check-list.
        /// </summary>
        public static string CreateCheckLists {
            get {
                return ResourceManager.GetString("CreateCheckLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description: *.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description length should be between 2 - 250 characters.
        /// </summary>
        public static string Description_length_validation {
            get {
                return ResourceManager.GetString("Description_length_validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description: .
        /// </summary>
        public static string Description_Search {
            get {
                return ResourceManager.GetString("Description_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to description.
        /// </summary>
        public static string description_ViewSearch {
            get {
                return ResourceManager.GetString("description_ViewSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check-list Group: *.
        /// </summary>
        public static string GroupID {
            get {
                return ResourceManager.GetString("GroupID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check-list Groups: .
        /// </summary>
        public static string groupID_Search {
            get {
                return ResourceManager.GetString("groupID_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check-list Groups.
        /// </summary>
        public static string GroupID_ViewSearch {
            get {
                return ResourceManager.GetString("GroupID_ViewSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name: *.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name length should be between 5 - 100 characters.
        /// </summary>
        public static string name_length_validation {
            get {
                return ResourceManager.GetString("name_length_validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name: .
        /// </summary>
        public static string name_Search {
            get {
                return ResourceManager.GetString("name_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name.
        /// </summary>
        public static string name_ViewSearch {
            get {
                return ResourceManager.GetString("name_ViewSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check-list name already exist !.
        /// </summary>
        public static string nameAlreadyExist {
            get {
                return ResourceManager.GetString("nameAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select check-list groups.
        /// </summary>
        public static string provide_avalid_Group {
            get {
                return ResourceManager.GetString("provide_avalid_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a valid check-list description.
        /// </summary>
        public static string provide_valid_Description {
            get {
                return ResourceManager.GetString("provide_valid_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a valid check-list name.
        /// </summary>
        public static string provide_valid_Name {
            get {
                return ResourceManager.GetString("provide_valid_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Check-lists.
        /// </summary>
        public static string SearchCheck_lists {
            get {
                return ResourceManager.GetString("SearchCheck_lists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Check-list.
        /// </summary>
        public static string UpdateCheckLists {
            get {
                return ResourceManager.GetString("UpdateCheckLists", resourceCulture);
            }
        }
    }
}
