//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Complaint {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Complaint() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QA.Localization.Complaint", typeof(Complaint).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach File.
        /// </summary>
        public static string Attachment_AddAttached {
            get {
                return ResourceManager.GetString("Attachment_AddAttached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment length should be less than 100 characters.
        /// </summary>
        public static string Comment_length_validation {
            get {
                return ResourceManager.GetString("Comment_length_validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments: *.
        /// </summary>
        public static string comments {
            get {
                return ResourceManager.GetString("comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments:.
        /// </summary>
        public static string Comments_Search {
            get {
                return ResourceManager.GetString("Comments_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string comments_ViewSearch {
            get {
                return ResourceManager.GetString("comments_ViewSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complaint Added Successfully.
        /// </summary>
        public static string ComplaintAddedSuccessfully {
            get {
                return ResourceManager.GetString("ComplaintAddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complaint Details.
        /// </summary>
        public static string ComplaintDetails {
            get {
                return ResourceManager.GetString("ComplaintDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complaint ID: .
        /// </summary>
        public static string complaintID {
            get {
                return ResourceManager.GetString("complaintID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complaint ID Not Available in DB.
        /// </summary>
        public static string ComplaintID_Not_Available_inDB {
            get {
                return ResourceManager.GetString("ComplaintID_Not_Available_inDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complaint Status: .
        /// </summary>
        public static string complaintStatus {
            get {
                return ResourceManager.GetString("complaintStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complaint Status:.
        /// </summary>
        public static string ComplaintStatus_Search {
            get {
                return ResourceManager.GetString("ComplaintStatus_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complaint Status.
        /// </summary>
        public static string complaintStatus_ViewSearch {
            get {
                return ResourceManager.GetString("complaintStatus_ViewSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Select - .
        /// </summary>
        public static string CRDDL_EmptyList {
            get {
                return ResourceManager.GetString("CRDDL_EmptyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Complaint.
        /// </summary>
        public static string CreateComplaint {
            get {
                return ResourceManager.GetString("CreateComplaint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CR: *.
        /// </summary>
        public static string CRID {
            get {
                return ResourceManager.GetString("CRID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CR: .
        /// </summary>
        public static string CRID_Search {
            get {
                return ResourceManager.GetString("CRID_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CR.
        /// </summary>
        public static string CRID_ViewSearch {
            get {
                return ResourceManager.GetString("CRID_ViewSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complaint description: *.
        /// </summary>
        public static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complaint length should be between 5 - 200 characters.
        /// </summary>
        public static string Description_length_validation {
            get {
                return ResourceManager.GetString("Description_length_validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complaint description: .
        /// </summary>
        public static string description_Search {
            get {
                return ResourceManager.GetString("description_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complaint description.
        /// </summary>
        public static string description_ViewSearch {
            get {
                return ResourceManager.GetString("description_ViewSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Not available.
        /// </summary>
        public static string Download_NA {
            get {
                return ResourceManager.GetString("Download_NA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string DownloadAttachment {
            get {
                return ResourceManager.GetString("DownloadAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification List.
        /// </summary>
        public static string NotificationList {
            get {
                return ResourceManager.GetString("NotificationList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification List.
        /// </summary>
        public static string NotificationList_ViewSearch {
            get {
                return ResourceManager.GetString("NotificationList_ViewSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project: .
        /// </summary>
        public static string ProjectID_Search {
            get {
                return ResourceManager.GetString("ProjectID_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Name: *.
        /// </summary>
        public static string ProjectName {
            get {
                return ResourceManager.GetString("ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Name.
        /// </summary>
        public static string ProjectName_ViewSearch {
            get {
                return ResourceManager.GetString("ProjectName_ViewSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Project CR .
        /// </summary>
        public static string provide_valid_CRID {
            get {
                return ResourceManager.GetString("provide_valid_CRID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please provide valid Project.
        /// </summary>
        public static string provide_valid_ProjectID {
            get {
                return ResourceManager.GetString("provide_valid_ProjectID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Complaints.
        /// </summary>
        public static string SearchComplaints {
            get {
                return ResourceManager.GetString("SearchComplaints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted.
        /// </summary>
        public static string StatusDDL_Accepted {
            get {
                return ResourceManager.GetString("StatusDDL_Accepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Complaint.
        /// </summary>
        public static string StatusDDL_NewComplaint {
            get {
                return ResourceManager.GetString("StatusDDL_NewComplaint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejeceted.
        /// </summary>
        public static string StatusDDL_Rejected {
            get {
                return ResourceManager.GetString("StatusDDL_Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - Select - .
        /// </summary>
        public static string StatusDDL_Select {
            get {
                return ResourceManager.GetString("StatusDDL_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Under Investigation.
        /// </summary>
        public static string StatusDDL_UnderInvestigation {
            get {
                return ResourceManager.GetString("StatusDDL_UnderInvestigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Complaint.
        /// </summary>
        public static string UpdateComplaint {
            get {
                return ResourceManager.GetString("UpdateComplaint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please provide a vaid complaint Comment.
        /// </summary>
        public static string valid_Comment {
            get {
                return ResourceManager.GetString("valid_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please provide a vaid complaint Description.
        /// </summary>
        public static string valid_Description {
            get {
                return ResourceManager.GetString("valid_Description", resourceCulture);
            }
        }
    }
}
