//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ContactDetails {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ContactDetails() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QA.Localization.ContactDetails", typeof(ContactDetails).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Line Length Should be Between 5 - 200 characters.
        /// </summary>
        public static string Address_length_validation {
            get {
                return ResourceManager.GetString("Address_length_validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Line: .
        /// </summary>
        public static string AddressLine {
            get {
                return ResourceManager.GetString("AddressLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Line.
        /// </summary>
        public static string AddressLine_ViewSearch {
            get {
                return ResourceManager.GetString("AddressLine_ViewSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Details ID.
        /// </summary>
        public static string CDID {
            get {
                return ResourceManager.GetString("CDID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CDID Search.
        /// </summary>
        public static string CDID_ViewSearch {
            get {
                return ResourceManager.GetString("CDID_ViewSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Details Added Successfully.
        /// </summary>
        public static string ContactDetailsAddedSuccessfully {
            get {
                return ResourceManager.GetString("ContactDetailsAddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Details Details.
        /// </summary>
        public static string ContactDetailsDetails {
            get {
                return ResourceManager.GetString("ContactDetailsDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contact Details ID Not Available in DB.
        /// </summary>
        public static string contactDetailsID_Not_Available_inDB {
            get {
                return ResourceManager.GetString("contactDetailsID_Not_Available_inDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Contact Details.
        /// </summary>
        public static string CreateContactDetails {
            get {
                return ResourceManager.GetString("CreateContactDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail Length Should be Between 5 - 50 characters.
        /// </summary>
        public static string Email_Length_Validation {
            get {
                return ResourceManager.GetString("Email_Length_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to email Search:.
        /// </summary>
        public static string email_Search {
            get {
                return ResourceManager.GetString("email_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to email Search.
        /// </summary>
        public static string email_ViewSearch {
            get {
                return ResourceManager.GetString("email_ViewSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail Address: *.
        /// </summary>
        public static string emailAddress {
            get {
                return ResourceManager.GetString("emailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax: .
        /// </summary>
        public static string fax {
            get {
                return ResourceManager.GetString("fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        public static string fax_ViewSearch {
            get {
                return ResourceManager.GetString("fax_ViewSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mobile Search.
        /// </summary>
        public static string mobile_ViewSearch {
            get {
                return ResourceManager.GetString("mobile_ViewSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Number: *.
        /// </summary>
        public static string mobileNumber {
            get {
                return ResourceManager.GetString("mobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Number: .
        /// </summary>
        public static string mobileNumber_Search {
            get {
                return ResourceManager.GetString("mobileNumber_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Length Should be Between 5 - 20 characters.
        /// </summary>
        public static string Number_length_5_20 {
            get {
                return ResourceManager.GetString("Number_length_5_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Search.
        /// </summary>
        public static string Phone_ViewSearch {
            get {
                return ResourceManager.GetString("Phone_ViewSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to phone Number: .
        /// </summary>
        public static string phoneNumber {
            get {
                return ResourceManager.GetString("phoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Contact Detail.
        /// </summary>
        public static string SearchContactDetail {
            get {
                return ResourceManager.GetString("SearchContactDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Contact Details.
        /// </summary>
        public static string UpdateContactDetails {
            get {
                return ResourceManager.GetString("UpdateContactDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a valid E-mail Address.
        /// </summary>
        public static string valid_Email {
            get {
                return ResourceManager.GetString("valid_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a valid mobile number.
        /// </summary>
        public static string valid_Mobile {
            get {
                return ResourceManager.GetString("valid_Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to work Extention Number: .
        /// </summary>
        public static string workExtNumber {
            get {
                return ResourceManager.GetString("workExtNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to work Extention Number.
        /// </summary>
        public static string workExtNumber_ViewSearch {
            get {
                return ResourceManager.GetString("workExtNumber_ViewSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to work phone number: .
        /// </summary>
        public static string workPhoneNumber {
            get {
                return ResourceManager.GetString("workPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to work phone number.
        /// </summary>
        public static string workPhoneNumber_ViewSearch {
            get {
                return ResourceManager.GetString("workPhoneNumber_ViewSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work place: .
        /// </summary>
        public static string workPlace {
            get {
                return ResourceManager.GetString("workPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work place.
        /// </summary>
        public static string workPlace_ViewSearch {
            get {
                return ResourceManager.GetString("workPlace_ViewSearch", resourceCulture);
            }
        }
    }
}
