//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CR_TYPES_MAIN_CATEGORIES {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CR_TYPES_MAIN_CATEGORIES() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QA.Localization.CR_TYPES_MAIN_CATEGORIES", typeof(CR_TYPES_MAIN_CATEGORIES).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Details.
        /// </summary>
        public static string CR_Type_MC_Details {
            get {
                return ResourceManager.GetString("CR_Type_MC_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create CR category.
        /// </summary>
        public static string Create_CR_Type_MC {
            get {
                return ResourceManager.GetString("Create_CR_Type_MC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create CR Type Main Category.
        /// </summary>
        public static string CreateCRTypeMainCategories {
            get {
                return ResourceManager.GetString("CreateCRTypeMainCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CR Type Main Category Details.
        /// </summary>
        public static string CRTypeMainCategoriesDetails {
            get {
                return ResourceManager.GetString("CRTypeMainCategoriesDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CR type Main Category ID Search.
        /// </summary>
        public static string CRtypeMainCatID_ViewSearch {
            get {
                return ResourceManager.GetString("CRtypeMainCatID_ViewSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Added Successfully.
        /// </summary>
        public static string CRTypeMCAddedSuccessfully {
            get {
                return ResourceManager.GetString("CRTypeMCAddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Occured While Adding new Category.
        /// </summary>
        public static string CRTypeMCAddError {
            get {
                return ResourceManager.GetString("CRTypeMCAddError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CR type Cateory ID Not Available in DB.
        /// </summary>
        public static string CRTYPEMCID_Not_Available_inDB {
            get {
                return ResourceManager.GetString("CRTYPEMCID_Not_Available_inDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description: *.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description length should be between 2 - 250 characters.
        /// </summary>
        public static string Description_length_validation {
            get {
                return ResourceManager.GetString("Description_length_validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        public static string Description_Search {
            get {
                return ResourceManager.GetString("Description_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to description.
        /// </summary>
        public static string description_ViewSearch {
            get {
                return ResourceManager.GetString("description_ViewSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category ID: .
        /// </summary>
        public static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name: *.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name length should be between 5 - 100 characters.
        /// </summary>
        public static string Name_length_validation {
            get {
                return ResourceManager.GetString("Name_length_validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string Name_Search {
            get {
                return ResourceManager.GetString("Name_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name.
        /// </summary>
        public static string name_ViewSearch {
            get {
                return ResourceManager.GetString("name_ViewSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category name Already Exist!.
        /// </summary>
        public static string NameAlreadyExist {
            get {
                return ResourceManager.GetString("NameAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please provide a valid Description.
        /// </summary>
        public static string provide_valid_Description {
            get {
                return ResourceManager.GetString("provide_valid_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please provide a valid category Name.
        /// </summary>
        public static string provide_valid_Name {
            get {
                return ResourceManager.GetString("provide_valid_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Categories.
        /// </summary>
        public static string Search_Categories {
            get {
                return ResourceManager.GetString("Search_Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update CR Type Main Categories.
        /// </summary>
        public static string UpdateCRTypeMainCategories {
            get {
                return ResourceManager.GetString("UpdateCRTypeMainCategories", resourceCulture);
            }
        }
    }
}
