//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CR_Workflow {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CR_Workflow() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QA.Localization.CR_Workflow", typeof(CR_Workflow).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept CR.
        /// </summary>
        public static string Accept_CR {
            get {
                return ResourceManager.GetString("Accept_CR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Complaint.
        /// </summary>
        public static string Add_Complaint {
            get {
                return ResourceManager.GetString("Add_Complaint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NA.
        /// </summary>
        public static string Add_Complaint_NotAllowed {
            get {
                return ResourceManager.GetString("Add_Complaint_NotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NA.
        /// </summary>
        public static string AddAttach_NotAllowed {
            get {
                return ResourceManager.GetString("AddAttach_NotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Attachments.
        /// </summary>
        public static string AddAttachments {
            get {
                return ResourceManager.GetString("AddAttachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign CR.
        /// </summary>
        public static string Assign_Cr {
            get {
                return ResourceManager.GetString("Assign_Cr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Assigned to your user successfully.
        /// </summary>
        public static string Assigned_To_Success {
            get {
                return ResourceManager.GetString("Assigned_To_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned CR&apos;s Retrieved Successfully.
        /// </summary>
        public static string AssignedCRRetrievedSuccess {
            get {
                return ResourceManager.GetString("AssignedCRRetrievedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach CR Files.
        /// </summary>
        public static string AttachCRFiles {
            get {
                return ResourceManager.GetString("AttachCRFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add attachments.
        /// </summary>
        public static string AttachFiles {
            get {
                return ResourceManager.GetString("AttachFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachments Retrieved Successfuly.
        /// </summary>
        public static string AttachmentRetrievedSuccess {
            get {
                return ResourceManager.GetString("AttachmentRetrievedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close CR.
        /// </summary>
        public static string CloseCR {
            get {
                return ResourceManager.GetString("CloseCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NA.
        /// </summary>
        public static string CloseCR_NotAllowed {
            get {
                return ResourceManager.GetString("CloseCR_NotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contractor.
        /// </summary>
        public static string Contractor {
            get {
                return ResourceManager.GetString("Contractor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CR .
        /// </summary>
        public static string CR {
            get {
                return ResourceManager.GetString("CR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CR Assigned Successfully.
        /// </summary>
        public static string CR_Assigned_Successfully {
            get {
                return ResourceManager.GetString("CR_Assigned_Successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CR Group.
        /// </summary>
        public static string CR_Group {
            get {
                return ResourceManager.GetString("CR_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CR Recieved Successfully.
        /// </summary>
        public static string CR_Recieved_Successfully {
            get {
                return ResourceManager.GetString("CR_Recieved_Successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CR status.
        /// </summary>
        public static string CR_Status {
            get {
                return ResourceManager.GetString("CR Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CR Type.
        /// </summary>
        public static string CR_Type {
            get {
                return ResourceManager.GetString("CR_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CR ID.
        /// </summary>
        public static string CRID {
            get {
                return ResourceManager.GetString("CRID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CR Main-category.
        /// </summary>
        public static string CRMC {
            get {
                return ResourceManager.GetString("CRMC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute.
        /// </summary>
        public static string ExecuteCR {
            get {
                return ResourceManager.GetString("ExecuteCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute CR.
        /// </summary>
        public static string ExecuteCR_Header {
            get {
                return ResourceManager.GetString("ExecuteCR_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CR Sample Geographical Premises should be within CR premises.
        /// </summary>
        public static string Map_CRSample_Validation_Location {
            get {
                return ResourceManager.GetString("Map_CRSample_Validation_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CR not exist or not assigned to the user !.
        /// </summary>
        public static string NotAssignedCR {
            get {
                return ResourceManager.GetString("NotAssignedCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending CR&apos;s Receievd Successfully.
        /// </summary>
        public static string PendingReceieved {
            get {
                return ResourceManager.GetString("PendingReceieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Item.
        /// </summary>
        public static string Project_Item {
            get {
                return ResourceManager.GetString("Project_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide sample length.
        /// </summary>
        public static string provide_sampleLength {
            get {
                return ResourceManager.GetString("provide_sampleLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide sample maker.
        /// </summary>
        public static string provide_sampleMaker {
            get {
                return ResourceManager.GetString("provide_sampleMaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide sample Size.
        /// </summary>
        public static string provide_sampleSize {
            get {
                return ResourceManager.GetString("provide_sampleSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide sample Unit.
        /// </summary>
        public static string provide_sampleUnit {
            get {
                return ResourceManager.GetString("provide_sampleUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recieve.
        /// </summary>
        public static string Receieve_CR {
            get {
                return ResourceManager.GetString("Receieve_CR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration date.
        /// </summary>
        public static string Registration_Date {
            get {
                return ResourceManager.GetString("Registration_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject CR.
        /// </summary>
        public static string Reject_CR {
            get {
                return ResourceManager.GetString("Reject_CR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject Reason.
        /// </summary>
        public static string Reject_Reason {
            get {
                return ResourceManager.GetString("Reject_Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide Reject Reason.
        /// </summary>
        public static string RejectCR_RejectReason_Validation {
            get {
                return ResourceManager.GetString("RejectCR_RejectReason_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Location should be determined.
        /// </summary>
        public static string Sample_Location_Validation {
            get {
                return ResourceManager.GetString("Sample_Location_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Length: .
        /// </summary>
        public static string sampleLength {
            get {
                return ResourceManager.GetString("sampleLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample length between 5 - 50 digits.
        /// </summary>
        public static string sampleLength_validation {
            get {
                return ResourceManager.GetString("sampleLength_validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Maker: .
        /// </summary>
        public static string sampleMaker {
            get {
                return ResourceManager.GetString("sampleMaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Size: .
        /// </summary>
        public static string sampleSize {
            get {
                return ResourceManager.GetString("sampleSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample size length between 5 - 50 digits.
        /// </summary>
        public static string sampleSize_validation {
            get {
                return ResourceManager.GetString("sampleSize_validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample unit: .
        /// </summary>
        public static string sampleUnit {
            get {
                return ResourceManager.GetString("sampleUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search All CR&apos;s.
        /// </summary>
        public static string SearchAllCrs {
            get {
                return ResourceManager.GetString("SearchAllCrs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Assigned CR&apos;s.
        /// </summary>
        public static string SearchAssignedCrs {
            get {
                return ResourceManager.GetString("SearchAssignedCrs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Pending CR&apos;s.
        /// </summary>
        public static string SearchPendingCrs {
            get {
                return ResourceManager.GetString("SearchPendingCrs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update CR.
        /// </summary>
        public static string UpdateCR {
            get {
                return ResourceManager.GetString("UpdateCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Attachments.
        /// </summary>
        public static string View_Attachments {
            get {
                return ResourceManager.GetString("View_Attachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NA.
        /// </summary>
        public static string View_Attachments_NotAllowed {
            get {
                return ResourceManager.GetString("View_Attachments_NotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View CR.
        /// </summary>
        public static string View_CR_Report {
            get {
                return ResourceManager.GetString("View_CR_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string ViewAttachments_Download {
            get {
                return ResourceManager.GetString("ViewAttachments_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NA.
        /// </summary>
        public static string ViewAttachments_Download_NotAvailable {
            get {
                return ResourceManager.GetString("ViewAttachments_Download_NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment Maker.
        /// </summary>
        public static string ViewAttachments_Maker {
            get {
                return ResourceManager.GetString("ViewAttachments_Maker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Category.
        /// </summary>
        public static string ViewAttachments_SampleCategory {
            get {
                return ResourceManager.GetString("ViewAttachments_SampleCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Code.
        /// </summary>
        public static string ViewAttachments_SampleCode {
            get {
                return ResourceManager.GetString("ViewAttachments_SampleCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Result.
        /// </summary>
        public static string ViewAttachments_SampleResult {
            get {
                return ResourceManager.GetString("ViewAttachments_SampleResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Test.
        /// </summary>
        public static string ViewAttachments_SampleTest {
            get {
                return ResourceManager.GetString("ViewAttachments_SampleTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الطلب: .
        /// </summary>
        public static string ViewCR_CR_DateTime {
            get {
                return ResourceManager.GetString("ViewCR_CR_DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الطلب: .
        /// </summary>
        public static string ViewCR_CR_ID {
            get {
                return ResourceManager.GetString("ViewCR_CR_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المقاول: .
        /// </summary>
        public static string ViewCR_CR_Owner {
            get {
                return ResourceManager.GetString("ViewCR_CR_Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تفاصيل الطلب: .
        /// </summary>
        public static string ViewCR_CR_Type {
            get {
                return ResourceManager.GetString("ViewCR_CR_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طلب فحص.
        /// </summary>
        public static string ViewCR_PageHeader_ReportName {
            get {
                return ResourceManager.GetString("ViewCR_PageHeader_ReportName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المختبر الخاص: .
        /// </summary>
        public static string ViewCR_PO_AuthLab {
            get {
                return ResourceManager.GetString("ViewCR_PO_AuthLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأستشارى: .
        /// </summary>
        public static string ViewCR_PO_ConsultantEng {
            get {
                return ResourceManager.GetString("ViewCR_PO_ConsultantEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأداره: .
        /// </summary>
        public static string ViewCR_PO_Department {
            get {
                return ResourceManager.GetString("ViewCR_PO_Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوحده: .
        /// </summary>
        public static string ViewCR_PO_DepSection {
            get {
                return ResourceManager.GetString("ViewCR_PO_DepSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الجهه المشرفه:.
        /// </summary>
        public static string ViewCR_PO_ProjectOwner {
            get {
                return ResourceManager.GetString("ViewCR_PO_ProjectOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مهندس مشرف: .
        /// </summary>
        public static string ViewCR_PO_SuperEng {
            get {
                return ResourceManager.GetString("ViewCR_PO_SuperEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ: .
        /// </summary>
        public static string ViewCR_Project_Date {
            get {
                return ResourceManager.GetString("ViewCR_Project_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بند المشروع: .
        /// </summary>
        public static string ViewCR_Project_MileStone {
            get {
                return ResourceManager.GetString("ViewCR_Project_MileStone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أسم المشروع: .
        /// </summary>
        public static string ViewCR_Project_Name {
            get {
                return ResourceManager.GetString("ViewCR_Project_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سمك العينه: .
        /// </summary>
        public static string ViewCR_Sample_Length {
            get {
                return ResourceManager.GetString("ViewCR_Sample_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صانع العينه: .
        /// </summary>
        public static string ViewCR_Sample_Maker {
            get {
                return ResourceManager.GetString("ViewCR_Sample_Maker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حجم العينه: .
        /// </summary>
        public static string ViewCR_Sample_Size {
            get {
                return ResourceManager.GetString("ViewCR_Sample_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وحده القياس: .
        /// </summary>
        public static string ViewCR_Sample_Unit {
            get {
                return ResourceManager.GetString("ViewCR_Sample_Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عرض طلب الفحص.
        /// </summary>
        public static string ViewCR_ScreenTitle {
            get {
                return ResourceManager.GetString("ViewCR_ScreenTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بيانات الطلب.
        /// </summary>
        public static string ViewCR_SubHeader_CRDetails {
            get {
                return ResourceManager.GetString("ViewCR_SubHeader_CRDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بيانات المشروع.
        /// </summary>
        public static string ViewCR_SubHeader_ProjectDetails {
            get {
                return ResourceManager.GetString("ViewCR_SubHeader_ProjectDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بيانات الجهه المشرفه.
        /// </summary>
        public static string ViewCR_SubHeader_ProjectOwner {
            get {
                return ResourceManager.GetString("ViewCR_SubHeader_ProjectOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بيانات العينه.
        /// </summary>
        public static string ViewCR_SubHeader_SampleDetails {
            get {
                return ResourceManager.GetString("ViewCR_SubHeader_SampleDetails", resourceCulture);
            }
        }
    }
}
