//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CRTYPEGroup {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CRTYPEGroup() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QA.Localization.CRTYPEGroup", typeof(CRTYPEGroup).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create CR Type Group.
        /// </summary>
        public static string CreateCRTypeGroup {
            get {
                return ResourceManager.GetString("CreateCRTypeGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CR category: *.
        /// </summary>
        public static string CRTMCID {
            get {
                return ResourceManager.GetString("CRTMCID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CR category: .
        /// </summary>
        public static string CRTMCID_Search {
            get {
                return ResourceManager.GetString("CRTMCID_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CR category.
        /// </summary>
        public static string CRTMCID_ViewSearch {
            get {
                return ResourceManager.GetString("CRTMCID_ViewSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CR Type Group Added Successfully.
        /// </summary>
        public static string CRTypeGroupAddedSuccessfully {
            get {
                return ResourceManager.GetString("CRTypeGroupAddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CR Type Group Details.
        /// </summary>
        public static string CRTypeGroupDetails {
            get {
                return ResourceManager.GetString("CRTypeGroupDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CR Type Group ID Not Available in DB.
        /// </summary>
        public static string CRTypeGroupID_Not_Available_inDB {
            get {
                return ResourceManager.GetString("CRTypeGroupID_Not_Available_inDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description: *.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description field should be 2- 250 characters.
        /// </summary>
        public static string Description_length_validation {
            get {
                return ResourceManager.GetString("Description_length_validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description: .
        /// </summary>
        public static string Description_Search {
            get {
                return ResourceManager.GetString("Description_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description_ViewSearch {
            get {
                return ResourceManager.GetString("Description_ViewSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group ID: .
        /// </summary>
        public static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name: *.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name length should be between 5 - 100 characters.
        /// </summary>
        public static string Name_length_validation {
            get {
                return ResourceManager.GetString("Name_length_validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name: .
        /// </summary>
        public static string Name_Search {
            get {
                return ResourceManager.GetString("Name_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name_ViewSearch {
            get {
                return ResourceManager.GetString("Name_ViewSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group name already exist !.
        /// </summary>
        public static string NameAlreadyExist {
            get {
                return ResourceManager.GetString("NameAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select CR category .
        /// </summary>
        public static string provide_valid_CRTMCID {
            get {
                return ResourceManager.GetString("provide_valid_CRTMCID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a valid description .
        /// </summary>
        public static string provide_valid_Description {
            get {
                return ResourceManager.GetString("provide_valid_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a valid group name.
        /// </summary>
        public static string provide_valid_Name {
            get {
                return ResourceManager.GetString("provide_valid_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Categories.
        /// </summary>
        public static string SearchCategories {
            get {
                return ResourceManager.GetString("SearchCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update CR Type Group.
        /// </summary>
        public static string UpdateCRTypeGroup {
            get {
                return ResourceManager.GetString("UpdateCRTypeGroup", resourceCulture);
            }
        }
    }
}
