//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CRType {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CRType() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QA.Localization.CRType", typeof(CRType).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a valid Description.
        /// </summary>
        public static string avalid_Description {
            get {
                return ResourceManager.GetString("avalid_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a valid name.
        /// </summary>
        public static string avalid_Name {
            get {
                return ResourceManager.GetString("avalid_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category: *.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category: .
        /// </summary>
        public static string Category_Search {
            get {
                return ResourceManager.GetString("Category_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category_ViewSearch {
            get {
                return ResourceManager.GetString("Category_ViewSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create CR Type.
        /// </summary>
        public static string CreateCRType {
            get {
                return ResourceManager.GetString("CreateCRType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CR Main category: *.
        /// </summary>
        public static string CRTMCID {
            get {
                return ResourceManager.GetString("CRTMCID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CR Main category: .
        /// </summary>
        public static string CRTMCID_Search {
            get {
                return ResourceManager.GetString("CRTMCID_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CR Main category.
        /// </summary>
        public static string CRTMCID_ViewSearch {
            get {
                return ResourceManager.GetString("CRTMCID_ViewSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CR Type Added Successfully.
        /// </summary>
        public static string CRTypeAddedSuccessfully {
            get {
                return ResourceManager.GetString("CRTypeAddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CR Type Details.
        /// </summary>
        public static string CRTypeDetails {
            get {
                return ResourceManager.GetString("CRTypeDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CR Type ID Not Available in DB.
        /// </summary>
        public static string CRTypeID_Not_Available_inDB {
            get {
                return ResourceManager.GetString("CRTypeID_Not_Available_inDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cr Type ID Search.
        /// </summary>
        public static string CrTypeID_Search {
            get {
                return ResourceManager.GetString("CrTypeID_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CR Type Search.
        /// </summary>
        public static string CRTypeSearch {
            get {
                return ResourceManager.GetString("CRTypeSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check-up.
        /// </summary>
        public static string DDL_Category_Checkup {
            get {
                return ResourceManager.GetString("DDL_Category_Checkup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Without Sample.
        /// </summary>
        public static string DDL_Category_withoutSample {
            get {
                return ResourceManager.GetString("DDL_Category_withoutSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description: *.
        /// </summary>
        public static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CR type description should be between 5 - 200 characters.
        /// </summary>
        public static string Description_length_validation {
            get {
                return ResourceManager.GetString("Description_length_validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description: .
        /// </summary>
        public static string description_Search {
            get {
                return ResourceManager.GetString("description_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string description_ViewSearch {
            get {
                return ResourceManager.GetString("description_ViewSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CR Group: *.
        /// </summary>
        public static string groupID {
            get {
                return ResourceManager.GetString("groupID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CR Group: .
        /// </summary>
        public static string groupID_Search {
            get {
                return ResourceManager.GetString("groupID_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CR Group.
        /// </summary>
        public static string groupID_ViewSearch {
            get {
                return ResourceManager.GetString("groupID_ViewSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CR Type ID: .
        /// </summary>
        public static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name *.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CR type name should be between 5 - 100 characters.
        /// </summary>
        public static string Name_length_validation {
            get {
                return ResourceManager.GetString("Name_length_validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name .
        /// </summary>
        public static string name_Search {
            get {
                return ResourceManager.GetString("name_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string name_ViewSearch {
            get {
                return ResourceManager.GetString("name_ViewSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CR Type name already exist !.
        /// </summary>
        public static string NameAlreadyExist {
            get {
                return ResourceManager.GetString("NameAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Category.
        /// </summary>
        public static string provide_avalid_Category {
            get {
                return ResourceManager.GetString("provide_avalid_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select a CR group.
        /// </summary>
        public static string provide_avalid_groupID {
            get {
                return ResourceManager.GetString("provide_avalid_groupID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update CR Type.
        /// </summary>
        public static string UpdateCRType {
            get {
                return ResourceManager.GetString("UpdateCRType", resourceCulture);
            }
        }
    }
}
