//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Department {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Department() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QA.Localization.Department", typeof(Department).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a valid Department description.
        /// </summary>
        public static string avalid_Description {
            get {
                return ResourceManager.GetString("avalid_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a valid Department name.
        /// </summary>
        public static string avalid_Name {
            get {
                return ResourceManager.GetString("avalid_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Department.
        /// </summary>
        public static string CreateDepartment {
            get {
                return ResourceManager.GetString("CreateDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Added Successfully.
        /// </summary>
        public static string DepartmentAddedSuccessfully {
            get {
                return ResourceManager.GetString("DepartmentAddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Details.
        /// </summary>
        public static string DepartmentDetails {
            get {
                return ResourceManager.GetString("DepartmentDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department ID: .
        /// </summary>
        public static string departmentID {
            get {
                return ResourceManager.GetString("departmentID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department ID Not Available in DB.
        /// </summary>
        public static string DepartmentID_Not_Available_inDB {
            get {
                return ResourceManager.GetString("DepartmentID_Not_Available_inDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Updated Successfully.
        /// </summary>
        public static string DepartmentUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("DepartmentUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description: .
        /// </summary>
        public static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Description length should be between 5 - 200 characters.
        /// </summary>
        public static string Description_length_validation {
            get {
                return ResourceManager.GetString("Description_length_validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description: .
        /// </summary>
        public static string description_Search {
            get {
                return ResourceManager.GetString("description_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string description_ViewSearch {
            get {
                return ResourceManager.GetString("description_ViewSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department name: *.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department name length should be between 5 - 100 characters.
        /// </summary>
        public static string Name_length_validation {
            get {
                return ResourceManager.GetString("Name_length_validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department name: .
        /// </summary>
        public static string name_Search {
            get {
                return ResourceManager.GetString("name_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department name.
        /// </summary>
        public static string name_ViewSearch {
            get {
                return ResourceManager.GetString("name_ViewSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department name Already Exist !.
        /// </summary>
        public static string NameAlreadyExist {
            get {
                return ResourceManager.GetString("NameAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Owner: *.
        /// </summary>
        public static string projectOwnerID {
            get {
                return ResourceManager.GetString("projectOwnerID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Owner: .
        /// </summary>
        public static string projectOwnerID_Search {
            get {
                return ResourceManager.GetString("projectOwnerID_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Owner.
        /// </summary>
        public static string projectOwnerID_ViewSearch {
            get {
                return ResourceManager.GetString("projectOwnerID_ViewSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Project owner.
        /// </summary>
        public static string provide_avalid_POID {
            get {
                return ResourceManager.GetString("provide_avalid_POID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Departments.
        /// </summary>
        public static string SearchDepartments {
            get {
                return ResourceManager.GetString("SearchDepartments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Select Department -.
        /// </summary>
        public static string SelectDepartment {
            get {
                return ResourceManager.GetString("SelectDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ----- Select Project Owner -----.
        /// </summary>
        public static string SelectProjectOwner {
            get {
                return ResourceManager.GetString("SelectProjectOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Department.
        /// </summary>
        public static string UpdateDepartment {
            get {
                return ResourceManager.GetString("UpdateDepartment", resourceCulture);
            }
        }
    }
}
