//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FactoryType {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FactoryType() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QA.Localization.FactoryType", typeof(FactoryType).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Factory Type.
        /// </summary>
        public static string Create_Factory_Type {
            get {
                return ResourceManager.GetString("Create_Factory_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factory Type description length should be between 2 - 250 characters.
        /// </summary>
        public static string Factory_Type_Desc_length_should_be_between_2_250_characters {
            get {
                return ResourceManager.GetString("Factory_Type_Desc_length_should_be_between_2_250_characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factory type Description.
        /// </summary>
        public static string Factory_type_Description {
            get {
                return ResourceManager.GetString("Factory_type_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factory Type Details.
        /// </summary>
        public static string Factory_Type_Details {
            get {
                return ResourceManager.GetString("Factory_Type_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factory Type ID.
        /// </summary>
        public static string Factory_Type_ID {
            get {
                return ResourceManager.GetString("Factory_Type_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factory type name *.
        /// </summary>
        public static string Factory_type_name {
            get {
                return ResourceManager.GetString("Factory_type_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factory Type name length should be between 5 - 100 characters.
        /// </summary>
        public static string Factory_Type_name_length_should_be_between_5_100_characters {
            get {
                return ResourceManager.GetString("Factory_Type_name_length_should_be_between_5_100_characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factory type name.
        /// </summary>
        public static string Factory_type_name_NotRequired {
            get {
                return ResourceManager.GetString("Factory_type_name_NotRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factory Type Added Successfully.
        /// </summary>
        public static string FactoryTypeAddedSuccessfully {
            get {
                return ResourceManager.GetString("FactoryTypeAddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Occured While Adding new Factory Type.
        /// </summary>
        public static string FactoryTypeAddError {
            get {
                return ResourceManager.GetString("FactoryTypeAddError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factory Type ID not available in DB !.
        /// </summary>
        public static string FactoryTypeID_Not_Available_inDB {
            get {
                return ResourceManager.GetString("FactoryTypeID_Not_Available_inDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factory Type name Already Exist!.
        /// </summary>
        public static string FactoryTypenameAlreadyExist {
            get {
                return ResourceManager.GetString("FactoryTypenameAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factory Type Updated Successfully.
        /// </summary>
        public static string FactoryTypeUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("FactoryTypeUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please provide a valid Factory Type Description.
        /// </summary>
        public static string please_provide_avalid_Factory_Type_Description {
            get {
                return ResourceManager.GetString("please_provide_avalid_Factory_Type_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please provide a valid Factory Type Name.
        /// </summary>
        public static string please_provide_avalid_Factory_Type_Name {
            get {
                return ResourceManager.GetString("please_provide_avalid_Factory_Type_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Factory Types.
        /// </summary>
        public static string SearchFactoryTypes {
            get {
                return ResourceManager.GetString("SearchFactoryTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Characters Not Allowed.
        /// </summary>
        public static string Special_Characters_Not_Allowed {
            get {
                return ResourceManager.GetString("Special_Characters_Not_Allowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Factory Type.
        /// </summary>
        public static string Update_Factory_Type {
            get {
                return ResourceManager.GetString("Update_Factory_Type", resourceCulture);
            }
        }
    }
}
