//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Mixer {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mixer() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QA.Localization.Mixer", typeof(Mixer).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Mixer.
        /// </summary>
        public static string Create_Mixer {
            get {
                return ResourceManager.GetString("Create_Mixer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Mixer.
        /// </summary>
        public static string CreateMixer {
            get {
                return ResourceManager.GetString("CreateMixer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description: *.
        /// </summary>
        public static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to description length should be between 5 to 200 characters..
        /// </summary>
        public static string Description_length_validation {
            get {
                return ResourceManager.GetString("Description_length_validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description: .
        /// </summary>
        public static string description_Search {
            get {
                return ResourceManager.GetString("description_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string description_ViewSearch {
            get {
                return ResourceManager.GetString("description_ViewSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factory: *.
        /// </summary>
        public static string factoryID {
            get {
                return ResourceManager.GetString("factoryID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factory: .
        /// </summary>
        public static string factoryID_Search {
            get {
                return ResourceManager.GetString("factoryID_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factory.
        /// </summary>
        public static string factoryID_ViewSearch {
            get {
                return ResourceManager.GetString("factoryID_ViewSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mixer ID: .
        /// </summary>
        public static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mixer Details.
        /// </summary>
        public static string Mixer_Details {
            get {
                return ResourceManager.GetString("Mixer_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mixer Status: .
        /// </summary>
        public static string mixer_status {
            get {
                return ResourceManager.GetString("mixer_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mixer status length should be between 5 to 200 characters..
        /// </summary>
        public static string mixer_status_length_validation {
            get {
                return ResourceManager.GetString("mixer_status_length_validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mixer status:.
        /// </summary>
        public static string mixer_status_Search {
            get {
                return ResourceManager.GetString("mixer_status_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mixer status.
        /// </summary>
        public static string mixer_status_ViewSearch {
            get {
                return ResourceManager.GetString("mixer_status_ViewSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mixer Added Successfully.
        /// </summary>
        public static string MixerAddedSuccessfully {
            get {
                return ResourceManager.GetString("MixerAddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mixer Address lenth should be between 5 to 200 characters..
        /// </summary>
        public static string mixerAddress_length_validation {
            get {
                return ResourceManager.GetString("mixerAddress_length_validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mixer code: *.
        /// </summary>
        public static string mixerCode {
            get {
                return ResourceManager.GetString("mixerCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mixer code length should be between 5 to 50 characters..
        /// </summary>
        public static string mixerCode_length_validation {
            get {
                return ResourceManager.GetString("mixerCode_length_validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mixer code: .
        /// </summary>
        public static string MixerCode_Search {
            get {
                return ResourceManager.GetString("MixerCode_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mixer code.
        /// </summary>
        public static string mixerCode_ViewSearch {
            get {
                return ResourceManager.GetString("mixerCode_ViewSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mixer ID Not Available in DB.
        /// </summary>
        public static string MixerID_Not_Available_inDB {
            get {
                return ResourceManager.GetString("MixerID_Not_Available_inDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mixer model: .
        /// </summary>
        public static string mixerModel {
            get {
                return ResourceManager.GetString("mixerModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mixer Model length should be between 5 to 50 characters..
        /// </summary>
        public static string mixerModel_length_validation {
            get {
                return ResourceManager.GetString("mixerModel_length_validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mixer model: .
        /// </summary>
        public static string mixerModel_Search {
            get {
                return ResourceManager.GetString("mixerModel_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mixer model.
        /// </summary>
        public static string mixerModel_ViewSearch {
            get {
                return ResourceManager.GetString("mixerModel_ViewSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mixer Power: .
        /// </summary>
        public static string mixerPower {
            get {
                return ResourceManager.GetString("mixerPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mixer Power lenth should be between 5 to 200 characters..
        /// </summary>
        public static string mixerPower_length_validation {
            get {
                return ResourceManager.GetString("mixerPower_length_validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mixer Power: .
        /// </summary>
        public static string mixerPower_Search {
            get {
                return ResourceManager.GetString("mixerPower_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mixer Power.
        /// </summary>
        public static string mixerPower_ViewSearch {
            get {
                return ResourceManager.GetString("mixerPower_ViewSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mixer type: *.
        /// </summary>
        public static string mixerTypeID {
            get {
                return ResourceManager.GetString("mixerTypeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mixer type: .
        /// </summary>
        public static string MixerTypeID_Search {
            get {
                return ResourceManager.GetString("MixerTypeID_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mixer type.
        /// </summary>
        public static string mixerTypeID_ViewSearch {
            get {
                return ResourceManager.GetString("mixerTypeID_ViewSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mixer Name: *.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mixer name length should be between 5 to 100 characters..
        /// </summary>
        public static string Name_length_validation {
            get {
                return ResourceManager.GetString("Name_length_validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mixer Name: .
        /// </summary>
        public static string name_Search {
            get {
                return ResourceManager.GetString("name_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mixer Name.
        /// </summary>
        public static string Name_ViewSearch {
            get {
                return ResourceManager.GetString("Name_ViewSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mixer name Already Exist!.
        /// </summary>
        public static string NameAlreadyExist {
            get {
                return ResourceManager.GetString("NameAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select factory.
        /// </summary>
        public static string provide_avalid_factory {
            get {
                return ResourceManager.GetString("provide_avalid_factory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Mixer type.
        /// </summary>
        public static string provide_avalid_mixerType {
            get {
                return ResourceManager.GetString("provide_avalid_mixerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please provide a valid Description.
        /// </summary>
        public static string provide_valid_Description {
            get {
                return ResourceManager.GetString("provide_valid_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plesae provide a valid mixer status.
        /// </summary>
        public static string provide_valid_mixer_status {
            get {
                return ResourceManager.GetString("provide_valid_mixer_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please provide a valid Mixer Code.
        /// </summary>
        public static string provide_valid_mixerCode {
            get {
                return ResourceManager.GetString("provide_valid_mixerCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please provide a valid Mixer Model.
        /// </summary>
        public static string provide_valid_mixerModel {
            get {
                return ResourceManager.GetString("provide_valid_mixerModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please provide a valid Mixer Power.
        /// </summary>
        public static string provide_valid_mixerPower {
            get {
                return ResourceManager.GetString("provide_valid_mixerPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please provide a valid mixer status.
        /// </summary>
        public static string provide_valid_mixerStatus {
            get {
                return ResourceManager.GetString("provide_valid_mixerStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please provide a valid Mixer Name.
        /// </summary>
        public static string provide_valid_Name {
            get {
                return ResourceManager.GetString("provide_valid_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Mixers.
        /// </summary>
        public static string SearchMixers {
            get {
                return ResourceManager.GetString("SearchMixers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Mixer.
        /// </summary>
        public static string UpdateMixer {
            get {
                return ResourceManager.GetString("UpdateMixer", resourceCulture);
            }
        }
    }
}
