//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProjectItem {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProjectItem() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QA.Localization.ProjectItem", typeof(ProjectItem).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount: *.
        /// </summary>
        public static string amount {
            get {
                return ResourceManager.GetString("amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a valid amount value !.
        /// </summary>
        public static string Amount_Required_Validation {
            get {
                return ResourceManager.GetString("Amount_Required_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount Unit: *.
        /// </summary>
        public static string amountUnit {
            get {
                return ResourceManager.GetString("amountUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Project Item.
        /// </summary>
        public static string CreateProjectItem {
            get {
                return ResourceManager.GetString("CreateProjectItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description: *.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description length should be between 2 - 250 characters.
        /// </summary>
        public static string Description_Length_Validation {
            get {
                return ResourceManager.GetString("Description_Length_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a valid Project item description.
        /// </summary>
        public static string Description_Required_Validation {
            get {
                return ResourceManager.GetString("Description_Required_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description: .
        /// </summary>
        public static string Description_Search {
            get {
                return ResourceManager.GetString("Description_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Item ID: .
        /// </summary>
        public static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name: *.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name length should be between 5 - 100 characters.
        /// </summary>
        public static string Name_length_Validation {
            get {
                return ResourceManager.GetString("Name_length_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a valid Project item name.
        /// </summary>
        public static string Name_Required_Validation {
            get {
                return ResourceManager.GetString("Name_Required_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name: .
        /// </summary>
        public static string name_Search {
            get {
                return ResourceManager.GetString("name_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage.
        /// </summary>
        public static string percentage {
            get {
                return ResourceManager.GetString("percentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project: *.
        /// </summary>
        public static string projectID {
            get {
                return ResourceManager.GetString("projectID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project: .
        /// </summary>
        public static string projectID_Search {
            get {
                return ResourceManager.GetString("projectID_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Item Search.
        /// </summary>
        public static string ProjectItem_Search {
            get {
                return ResourceManager.GetString("ProjectItem_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Item name already exist in the same project !.
        /// </summary>
        public static string ProjectItemAlreadyExist {
            get {
                return ResourceManager.GetString("ProjectItemAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Item Details.
        /// </summary>
        public static string ProjectItemDetails {
            get {
                return ResourceManager.GetString("ProjectItemDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to project Item ID Not Available in DB.
        /// </summary>
        public static string projectItemID_Not_Available_inDB {
            get {
                return ResourceManager.GetString("projectItemID_Not_Available_inDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Item ID Search.
        /// </summary>
        public static string ProjectItemID_Search {
            get {
                return ResourceManager.GetString("ProjectItemID_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Items Added Successfully.
        /// </summary>
        public static string ProjectItemsAddedSuccessfully {
            get {
                return ResourceManager.GetString("ProjectItemsAddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Amount unit.
        /// </summary>
        public static string provide_avalid_AmountUnit {
            get {
                return ResourceManager.GetString("provide_avalid_AmountUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select project.
        /// </summary>
        public static string provide_avalid_projectID {
            get {
                return ResourceManager.GetString("provide_avalid_projectID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Project Item.
        /// </summary>
        public static string UpdateProjectItem {
            get {
                return ResourceManager.GetString("UpdateProjectItem", resourceCulture);
            }
        }
    }
}
