//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Project {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Project() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QA.Localization.Project", typeof(Project).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorized lab: *.
        /// </summary>
        public static string authorizedLabID {
            get {
                return ResourceManager.GetString("authorizedLabID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorized lab: .
        /// </summary>
        public static string authorizedLabID_Search {
            get {
                return ResourceManager.GetString("authorizedLabID_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorized lab.
        /// </summary>
        public static string authorizedLabID_ViewSearch {
            get {
                return ResourceManager.GetString("authorizedLabID_ViewSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultant Assistant: *.
        /// </summary>
        public static string consultantAssistantID {
            get {
                return ResourceManager.GetString("consultantAssistantID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultant Assistant: .
        /// </summary>
        public static string consultantAssistantID_Search {
            get {
                return ResourceManager.GetString("consultantAssistantID_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultant Assistant.
        /// </summary>
        public static string consultantAssistantID_ViewSearch {
            get {
                return ResourceManager.GetString("consultantAssistantID_ViewSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultant: *.
        /// </summary>
        public static string consultantID {
            get {
                return ResourceManager.GetString("consultantID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultant: .
        /// </summary>
        public static string consultantID_Search {
            get {
                return ResourceManager.GetString("consultantID_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultant.
        /// </summary>
        public static string consultantID_ViewSearch {
            get {
                return ResourceManager.GetString("consultantID_ViewSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contractor assistant: *.
        /// </summary>
        public static string contractorAssistantID {
            get {
                return ResourceManager.GetString("contractorAssistantID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contractor assistant: .
        /// </summary>
        public static string contractorAssistantID_Search {
            get {
                return ResourceManager.GetString("contractorAssistantID_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contractor assistant.
        /// </summary>
        public static string contractorAssistantID_ViewSearch {
            get {
                return ResourceManager.GetString("contractorAssistantID_ViewSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contractor: *.
        /// </summary>
        public static string contractorID {
            get {
                return ResourceManager.GetString("contractorID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contractor: .
        /// </summary>
        public static string contractorID_Search {
            get {
                return ResourceManager.GetString("contractorID_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contractor.
        /// </summary>
        public static string contractorID_ViewSearch {
            get {
                return ResourceManager.GetString("contractorID_ViewSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Project.
        /// </summary>
        public static string CreateProject {
            get {
                return ResourceManager.GetString("CreateProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department: *.
        /// </summary>
        public static string departmentID {
            get {
                return ResourceManager.GetString("departmentID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department: .
        /// </summary>
        public static string departmentID_Search {
            get {
                return ResourceManager.GetString("departmentID_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string departmentID_ViewSearch {
            get {
                return ResourceManager.GetString("departmentID_ViewSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section: *.
        /// </summary>
        public static string departmentSectionID {
            get {
                return ResourceManager.GetString("departmentSectionID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section: .
        /// </summary>
        public static string departmentSectionID_Search {
            get {
                return ResourceManager.GetString("departmentSectionID_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section.
        /// </summary>
        public static string departmentSectionID_ViewSearch {
            get {
                return ResourceManager.GetString("departmentSectionID_ViewSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected End date: *.
        /// </summary>
        public static string endDate {
            get {
                return ResourceManager.GetString("endDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected End date: .
        /// </summary>
        public static string endDate_Search {
            get {
                return ResourceManager.GetString("endDate_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date From:.
        /// </summary>
        public static string endDate_Search_From {
            get {
                return ResourceManager.GetString("endDate_Search_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date To:.
        /// </summary>
        public static string endDate_Search_To {
            get {
                return ResourceManager.GetString("endDate_Search_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected End date.
        /// </summary>
        public static string endDate_ViewSearch {
            get {
                return ResourceManager.GetString("endDate_ViewSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project ID: .
        /// </summary>
        public static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kindly determine Project Location.
        /// </summary>
        public static string Map_Validation_ProjectLocation {
            get {
                return ResourceManager.GetString("Map_Validation_ProjectLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Milestones Should be determined.
        /// </summary>
        public static string MileStones_Validation {
            get {
                return ResourceManager.GetString("MileStones_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project name: *.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project name length should be between 5 - 50 characters.
        /// </summary>
        public static string Name_length_Validation {
            get {
                return ResourceManager.GetString("Name_length_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a valid project name !.
        /// </summary>
        public static string Name_Required_Validation {
            get {
                return ResourceManager.GetString("Name_Required_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project name: .
        /// </summary>
        public static string name_Search {
            get {
                return ResourceManager.GetString("name_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project name.
        /// </summary>
        public static string name_ViewSearch {
            get {
                return ResourceManager.GetString("name_ViewSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project name already exist !.
        /// </summary>
        public static string NameAlreadyExist {
            get {
                return ResourceManager.GetString("NameAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Added Successfully.
        /// </summary>
        public static string ProjectAddedSuccessfully {
            get {
                return ResourceManager.GetString("ProjectAddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Details.
        /// </summary>
        public static string ProjectDetails {
            get {
                return ResourceManager.GetString("ProjectDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to project ID Not Available in DB.
        /// </summary>
        public static string projectID_Not_Available_inDB {
            get {
                return ResourceManager.GetString("projectID_Not_Available_inDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Location.
        /// </summary>
        public static string ProjectLocation {
            get {
                return ResourceManager.GetString("ProjectLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Milestones.
        /// </summary>
        public static string ProjectMileStones {
            get {
                return ResourceManager.GetString("ProjectMileStones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to project owner: *.
        /// </summary>
        public static string projectOwnerID {
            get {
                return ResourceManager.GetString("projectOwnerID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to project owner: .
        /// </summary>
        public static string projectOwnerID_Search {
            get {
                return ResourceManager.GetString("projectOwnerID_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to project owner.
        /// </summary>
        public static string projectOwnerID_ViewSearch {
            get {
                return ResourceManager.GetString("projectOwnerID_ViewSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide Project Location.
        /// </summary>
        public static string ProjectShapeNotAdded {
            get {
                return ResourceManager.GetString("ProjectShapeNotAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Stakeholders.
        /// </summary>
        public static string ProjectStakeholders {
            get {
                return ResourceManager.GetString("ProjectStakeholders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Authorized lab.
        /// </summary>
        public static string provide_avalid_AuthorizedLab {
            get {
                return ResourceManager.GetString("provide_avalid_AuthorizedLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Consultant.
        /// </summary>
        public static string provide_avalid_Consultant {
            get {
                return ResourceManager.GetString("provide_avalid_Consultant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Consultant Assistant.
        /// </summary>
        public static string provide_avalid_ConsultantAssistant {
            get {
                return ResourceManager.GetString("provide_avalid_ConsultantAssistant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Contractor.
        /// </summary>
        public static string provide_avalid_Contractor {
            get {
                return ResourceManager.GetString("provide_avalid_Contractor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Contractor Assistant.
        /// </summary>
        public static string provide_avalid_ContractorAssistant {
            get {
                return ResourceManager.GetString("provide_avalid_ContractorAssistant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Department.
        /// </summary>
        public static string provide_avalid_Department {
            get {
                return ResourceManager.GetString("provide_avalid_Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Section.
        /// </summary>
        public static string provide_avalid_DepartmentSection {
            get {
                return ResourceManager.GetString("provide_avalid_DepartmentSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please select a valid Expected end date.
        /// </summary>
        public static string provide_avalid_EndDate {
            get {
                return ResourceManager.GetString("provide_avalid_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please select Project Owner.
        /// </summary>
        public static string provide_avalid_projectOwner {
            get {
                return ResourceManager.GetString("provide_avalid_projectOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select QA technician.
        /// </summary>
        public static string provide_avalid_QAtechnician {
            get {
                return ResourceManager.GetString("provide_avalid_QAtechnician", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please select Quality Engineer.
        /// </summary>
        public static string provide_avalid_QualityEng {
            get {
                return ResourceManager.GetString("provide_avalid_QualityEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please select a valid project start date.
        /// </summary>
        public static string provide_avalid_StartDate {
            get {
                return ResourceManager.GetString("provide_avalid_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Supervisor Engineer.
        /// </summary>
        public static string provide_avalid_SupervisorEng {
            get {
                return ResourceManager.GetString("provide_avalid_SupervisorEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Provide valid Project Registration date.
        /// </summary>
        public static string provide_valid_RegistrationDate {
            get {
                return ResourceManager.GetString("provide_valid_RegistrationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QA technician: *.
        /// </summary>
        public static string QATechnicianID {
            get {
                return ResourceManager.GetString("QATechnicianID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QA technician: .
        /// </summary>
        public static string QATechnicianID_Search {
            get {
                return ResourceManager.GetString("QATechnicianID_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QA technician.
        /// </summary>
        public static string QATechnicianID_ViewSearch {
            get {
                return ResourceManager.GetString("QATechnicianID_ViewSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality Engineer: .
        /// </summary>
        public static string QualityAssuranceEngID {
            get {
                return ResourceManager.GetString("QualityAssuranceEngID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality Engineer: .
        /// </summary>
        public static string QualityEngineerID_Search {
            get {
                return ResourceManager.GetString("QualityEngineerID_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality Engineer.
        /// </summary>
        public static string QualityEngineerID_ViewSearch {
            get {
                return ResourceManager.GetString("QualityEngineerID_ViewSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration date: .
        /// </summary>
        public static string registerDate {
            get {
                return ResourceManager.GetString("registerDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration date: .
        /// </summary>
        public static string registerDate_Search {
            get {
                return ResourceManager.GetString("registerDate_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Date From:.
        /// </summary>
        public static string registerDate_Search_From {
            get {
                return ResourceManager.GetString("registerDate_Search_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Date To:.
        /// </summary>
        public static string registerDate_Search_To {
            get {
                return ResourceManager.GetString("registerDate_Search_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration date.
        /// </summary>
        public static string registerDate_ViewSearch {
            get {
                return ResourceManager.GetString("registerDate_ViewSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المختبر: .
        /// </summary>
        public static string Report_ProjectDetails_AuthLab {
            get {
                return ResourceManager.GetString("Report_ProjectDetails_AuthLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to منتهي.
        /// </summary>
        public static string Report_ProjectDetails_Complaint_Closed {
            get {
                return ResourceManager.GetString("Report_ProjectDetails_Complaint_Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد حالات عدم التطابق: .
        /// </summary>
        public static string Report_ProjectDetails_Complaint_Details {
            get {
                return ResourceManager.GetString("Report_ProjectDetails_Complaint_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إجمالى.
        /// </summary>
        public static string Report_ProjectDetails_Complaint_Total {
            get {
                return ResourceManager.GetString("Report_ProjectDetails_Complaint_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جاري.
        /// </summary>
        public static string Report_ProjectDetails_Complaint_WIP {
            get {
                return ResourceManager.GetString("Report_ProjectDetails_Complaint_WIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأستشارى: .
        /// </summary>
        public static string Report_ProjectDetails_ConsEng {
            get {
                return ResourceManager.GetString("Report_ProjectDetails_ConsEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المقاول: .
        /// </summary>
        public static string Report_ProjectDetails_Contractor {
            get {
                return ResourceManager.GetString("Report_ProjectDetails_Contractor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to منتهى: .
        /// </summary>
        public static string Report_ProjectDetails_CR_Closed {
            get {
                return ResourceManager.GetString("Report_ProjectDetails_CR_Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حالات طلبات الفحص :.
        /// </summary>
        public static string Report_ProjectDetails_CR_Status {
            get {
                return ResourceManager.GetString("Report_ProjectDetails_CR_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد طلبات الفحص: .
        /// </summary>
        public static string Report_ProjectDetails_CR_Total {
            get {
                return ResourceManager.GetString("Report_ProjectDetails_CR_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جارى العمل: .
        /// </summary>
        public static string Report_ProjectDetails_CR_WIP {
            get {
                return ResourceManager.GetString("Report_ProjectDetails_CR_WIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الموافقه.
        /// </summary>
        public static string Report_ProjectDetails_CRStat_Accepted {
            get {
                return ResourceManager.GetString("Report_ProjectDetails_CRStat_Accepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المختبر الخاص.
        /// </summary>
        public static string Report_ProjectDetails_CRStat_AuthLab {
            get {
                return ResourceManager.GetString("Report_ProjectDetails_CRStat_AuthLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإستشاري.
        /// </summary>
        public static string Report_ProjectDetails_CRStat_ConsEng {
            get {
                return ResourceManager.GetString("Report_ProjectDetails_CRStat_ConsEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معلق.
        /// </summary>
        public static string Report_ProjectDetails_CRStat_Pending {
            get {
                return ResourceManager.GetString("Report_ProjectDetails_CRStat_Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مستلم.
        /// </summary>
        public static string Report_ProjectDetails_CRStat_Recieved {
            get {
                return ResourceManager.GetString("Report_ProjectDetails_CRStat_Recieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الرفض.
        /// </summary>
        public static string Report_ProjectDetails_CRStat_Rejected {
            get {
                return ResourceManager.GetString("Report_ProjectDetails_CRStat_Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المهندس المشرف.
        /// </summary>
        public static string Report_ProjectDetails_CRStat_SuperEng {
            get {
                return ResourceManager.GetString("Report_ProjectDetails_CRStat_SuperEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأداره: .
        /// </summary>
        public static string Report_ProjectDetails_Department {
            get {
                return ResourceManager.GetString("Report_ProjectDetails_Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الجهه المالكه: .
        /// </summary>
        public static string Report_ProjectDetails_ProjectOwner {
            get {
                return ResourceManager.GetString("Report_ProjectDetails_ProjectOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تقرير عن مشروع.
        /// </summary>
        public static string Report_ProjectDetails_ReportHeader {
            get {
                return ResourceManager.GetString("Report_ProjectDetails_ReportHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تقرير عن مشروع.
        /// </summary>
        public static string Report_ProjectDetails_ReportName {
            get {
                return ResourceManager.GetString("Report_ProjectDetails_ReportName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المطابق.
        /// </summary>
        public static string Report_ProjectDetails_Samples_Accepted {
            get {
                return ResourceManager.GetString("Report_ProjectDetails_Samples_Accepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العينات :.
        /// </summary>
        public static string Report_ProjectDetails_Samples_Details {
            get {
                return ResourceManager.GetString("Report_ProjectDetails_Samples_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا توجد بيانات عينات.
        /// </summary>
        public static string Report_ProjectDetails_Samples_Empty {
            get {
                return ResourceManager.GetString("Report_ProjectDetails_Samples_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غير المطابق.
        /// </summary>
        public static string Report_ProjectDetails_Samples_Rejected {
            get {
                return ResourceManager.GetString("Report_ProjectDetails_Samples_Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع العينة.
        /// </summary>
        public static string Report_ProjectDetails_Samples_Type {
            get {
                return ResourceManager.GetString("Report_ProjectDetails_Samples_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المهندس المشرف: .
        /// </summary>
        public static string Report_ProjectDetails_SuperEng {
            get {
                return ResourceManager.GetString("Report_ProjectDetails_SuperEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Projects.
        /// </summary>
        public static string SearchProjects {
            get {
                return ResourceManager.GetString("SearchProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miss-match Case.
        /// </summary>
        public static string SearchRes_CreateMissmatch {
            get {
                return ResourceManager.GetString("SearchRes_CreateMissmatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project start Date: *.
        /// </summary>
        public static string startDate {
            get {
                return ResourceManager.GetString("startDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project start Date: .
        /// </summary>
        public static string startDate_Search {
            get {
                return ResourceManager.GetString("startDate_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date From: .
        /// </summary>
        public static string startDate_Search_From {
            get {
                return ResourceManager.GetString("startDate_Search_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date To:.
        /// </summary>
        public static string startDate_Search_To {
            get {
                return ResourceManager.GetString("startDate_Search_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to start Date.
        /// </summary>
        public static string startDate_ViewSearch {
            get {
                return ResourceManager.GetString("startDate_ViewSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supervisor Engineer: *.
        /// </summary>
        public static string supervisorEngID {
            get {
                return ResourceManager.GetString("supervisorEngID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supervisor Engineer: .
        /// </summary>
        public static string supervisorEngID_Search {
            get {
                return ResourceManager.GetString("supervisorEngID_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supervisor Engineer.
        /// </summary>
        public static string supervisorEngID_ViewSearch {
            get {
                return ResourceManager.GetString("supervisorEngID_ViewSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string tbl_ProjMlstone_Add {
            get {
                return ResourceManager.GetString("tbl_ProjMlstone_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string tbl_ProjMlstone_Amount {
            get {
                return ResourceManager.GetString("tbl_ProjMlstone_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        public static string tbl_ProjMlstone_Amt_Unit {
            get {
                return ResourceManager.GetString("tbl_ProjMlstone_Amt_Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilogram.
        /// </summary>
        public static string tbl_ProjMlstone_AmtUnit_KG {
            get {
                return ResourceManager.GetString("tbl_ProjMlstone_AmtUnit_KG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilometer.
        /// </summary>
        public static string tbl_ProjMlstone_AmtUnit_KM {
            get {
                return ResourceManager.GetString("tbl_ProjMlstone_AmtUnit_KM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meter.
        /// </summary>
        public static string tbl_ProjMlstone_AmtUnit_M {
            get {
                return ResourceManager.GetString("tbl_ProjMlstone_AmtUnit_M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - Select - .
        /// </summary>
        public static string tbl_ProjMlstone_AmtUnit_Select {
            get {
                return ResourceManager.GetString("tbl_ProjMlstone_AmtUnit_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string tbl_ProjMlstone_Description {
            get {
                return ResourceManager.GetString("tbl_ProjMlstone_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project milestones - Fields Validation failed.
        /// </summary>
        public static string tbl_ProjMlstone_FieldsError {
            get {
                return ResourceManager.GetString("tbl_ProjMlstone_FieldsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milestone.
        /// </summary>
        public static string tbl_ProjMlstone_MileStone {
            get {
                return ResourceManager.GetString("tbl_ProjMlstone_MileStone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project %.
        /// </summary>
        public static string tbl_ProjMlstone_Percentage {
            get {
                return ResourceManager.GetString("tbl_ProjMlstone_Percentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to total project Milestones Percentage should be 100%.
        /// </summary>
        public static string tbl_ProjMlstone_Percentage_Validation {
            get {
                return ResourceManager.GetString("tbl_ProjMlstone_Percentage_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string tbl_ProjMlstone_Remove {
            get {
                return ResourceManager.GetString("tbl_ProjMlstone_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        public static string tbl_ProjMlstone_Remove_Btn {
            get {
                return ResourceManager.GetString("tbl_ProjMlstone_Remove_Btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #.
        /// </summary>
        public static string tbl_ProjMlstone_Serial {
            get {
                return ResourceManager.GetString("tbl_ProjMlstone_Serial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length validation 5 - 50..
        /// </summary>
        public static string tbl_ProjMlstone_Val_Length {
            get {
                return ResourceManager.GetString("tbl_ProjMlstone_Val_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numeric Values Only.
        /// </summary>
        public static string tbl_ProjMlstone_Val_NumericField {
            get {
                return ResourceManager.GetString("tbl_ProjMlstone_Val_NumericField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Field.
        /// </summary>
        public static string tbl_ProjMlstone_Val_Required {
            get {
                return ResourceManager.GetString("tbl_ProjMlstone_Val_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Characters Not Allowed.
        /// </summary>
        public static string tbl_ProjMlstone_Val_SpecialCharacters {
            get {
                return ResourceManager.GetString("tbl_ProjMlstone_Val_SpecialCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Project.
        /// </summary>
        public static string UpdateProject {
            get {
                return ResourceManager.GetString("UpdateProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string View_Project_Report {
            get {
                return ResourceManager.GetString("View_Project_Report", resourceCulture);
            }
        }
    }
}
