//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProjectOwner {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProjectOwner() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QA.Localization.ProjectOwner", typeof(ProjectOwner).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accountable: *.
        /// </summary>
        public static string accountable {
            get {
                return ResourceManager.GetString("accountable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accountable: .
        /// </summary>
        public static string Accountable_Search {
            get {
                return ResourceManager.GetString("Accountable_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accountable.
        /// </summary>
        public static string Accountable_ViewSearch {
            get {
                return ResourceManager.GetString("Accountable_ViewSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a valid accountable.
        /// </summary>
        public static string avalid_Accountable {
            get {
                return ResourceManager.GetString("avalid_Accountable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please provide a valid description.
        /// </summary>
        public static string avalid_Description {
            get {
                return ResourceManager.GetString("avalid_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Owner: .
        /// </summary>
        public static string boolIsOwner {
            get {
                return ResourceManager.GetString("boolIsOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Owner.
        /// </summary>
        public static string boolIsOwner_ViewSearch {
            get {
                return ResourceManager.GetString("boolIsOwner_ViewSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Project Owner.
        /// </summary>
        public static string CreateProjectOwner {
            get {
                return ResourceManager.GetString("CreateProjectOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description: .
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description: .
        /// </summary>
        public static string Description_Search {
            get {
                return ResourceManager.GetString("Description_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description_ViewSearch {
            get {
                return ResourceManager.GetString("Description_ViewSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accountable should be between 5 - 100 characters.
        /// </summary>
        public static string length_Accountable_validation {
            get {
                return ResourceManager.GetString("length_Accountable_validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project owner description length should be between 2 - 250 characters.
        /// </summary>
        public static string length_Description_validation {
            get {
                return ResourceManager.GetString("length_Description_validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name: .
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project owner name should be between 5 - 100 characters.
        /// </summary>
        public static string name_length_validation {
            get {
                return ResourceManager.GetString("name_length_validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string name_Search {
            get {
                return ResourceManager.GetString("name_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string name_ViewSearch {
            get {
                return ResourceManager.GetString("name_ViewSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Owner Details.
        /// </summary>
        public static string PODetails {
            get {
                return ResourceManager.GetString("PODetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Owner Type: *.
        /// </summary>
        public static string pOTID {
            get {
                return ResourceManager.GetString("pOTID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Owner Type: .
        /// </summary>
        public static string pOTID_Search {
            get {
                return ResourceManager.GetString("pOTID_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Owner Type.
        /// </summary>
        public static string pOTID_ViewSearch {
            get {
                return ResourceManager.GetString("pOTID_ViewSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Owner Added Successfully.
        /// </summary>
        public static string ProjectOwnerAddedSuccessfully {
            get {
                return ResourceManager.GetString("ProjectOwnerAddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Owner ID: .
        /// </summary>
        public static string projectOwnerID {
            get {
                return ResourceManager.GetString("projectOwnerID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to project owner ID Not Available in DB.
        /// </summary>
        public static string projectOwnerID_Not_Available_inDB {
            get {
                return ResourceManager.GetString("projectOwnerID_Not_Available_inDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Owner name Already exist !.
        /// </summary>
        public static string ProjectOwnerNameAlreadyExist {
            get {
                return ResourceManager.GetString("ProjectOwnerNameAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a valid Project owner name.
        /// </summary>
        public static string provide_avalid_Name {
            get {
                return ResourceManager.GetString("provide_avalid_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Project owner type.
        /// </summary>
        public static string provide_avalid_POT {
            get {
                return ResourceManager.GetString("provide_avalid_POT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Profile ID.
        /// </summary>
        public static string provide_avalid_ProfileID {
            get {
                return ResourceManager.GetString("provide_avalid_ProfileID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Select Project Owners -.
        /// </summary>
        public static string SearchProjectOwners {
            get {
                return ResourceManager.GetString("SearchProjectOwners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Project Owner.
        /// </summary>
        public static string UpdateProjectOwner {
            get {
                return ResourceManager.GetString("UpdateProjectOwner", resourceCulture);
            }
        }
    }
}
