//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PROJECT_OWNER_TYPE {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PROJECT_OWNER_TYPE() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QA.Localization.PROJECT_OWNER_TYPE", typeof(PROJECT_OWNER_TYPE).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Project Owner Type.
        /// </summary>
        public static string Create_ProjectOwner_Type {
            get {
                return ResourceManager.GetString("Create_ProjectOwner_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Project Owner Type.
        /// </summary>
        public static string CreateProjectOwnerType {
            get {
                return ResourceManager.GetString("CreateProjectOwnerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not-Vendor.
        /// </summary>
        public static string DDLIsVendor_NotVendor {
            get {
                return ResourceManager.GetString("DDLIsVendor_NotVendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - Select -.
        /// </summary>
        public static string DDLIsVendor_Select {
            get {
                return ResourceManager.GetString("DDLIsVendor_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor.
        /// </summary>
        public static string DDLIsVendor_Vendor {
            get {
                return ResourceManager.GetString("DDLIsVendor_Vendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please provide a valid Project Owner Type Description.
        /// </summary>
        public static string please_provide_avalid_ProjectOwner_Type_Description {
            get {
                return ResourceManager.GetString("please_provide_avalid_ProjectOwner_Type_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please provide a valid Project Owner Type Name.
        /// </summary>
        public static string please_provide_avalid_ProjectOwner_Type_Name {
            get {
                return ResourceManager.GetString("please_provide_avalid_ProjectOwner_Type_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description: .
        /// </summary>
        public static string POT_Description_Search {
            get {
                return ResourceManager.GetString("POT_Description_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Owner type Description.
        /// </summary>
        public static string POT_Description_ViewSearch {
            get {
                return ResourceManager.GetString("POT_Description_ViewSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Vendor: .
        /// </summary>
        public static string POT_IsVendor_Search {
            get {
                return ResourceManager.GetString("POT_IsVendor_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Vendor.
        /// </summary>
        public static string POT_IsVendor_ViewSearch {
            get {
                return ResourceManager.GetString("POT_IsVendor_ViewSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name: .
        /// </summary>
        public static string POT_name_Search {
            get {
                return ResourceManager.GetString("POT_name_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Owner type name.
        /// </summary>
        public static string POT_name_ViewSearch {
            get {
                return ResourceManager.GetString("POT_name_ViewSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Owner Type description length should be between 2 - 250 characters.
        /// </summary>
        public static string ProjectOwner_Type_Desc_length_should_be_between_2_250_characters {
            get {
                return ResourceManager.GetString("ProjectOwner_Type_Desc_length_should_be_between_2_250_characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Owner type Description:.
        /// </summary>
        public static string ProjectOwner_type_Description {
            get {
                return ResourceManager.GetString("ProjectOwner_type_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Owner Type Details.
        /// </summary>
        public static string ProjectOwner_Type_Details {
            get {
                return ResourceManager.GetString("ProjectOwner_Type_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Owner Type ID.
        /// </summary>
        public static string ProjectOwner_Type_ID {
            get {
                return ResourceManager.GetString("ProjectOwner_Type_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Owner type name: *.
        /// </summary>
        public static string ProjectOwner_type_name {
            get {
                return ResourceManager.GetString("ProjectOwner_type_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Owner Type name length should be between 5 - 100 characters.
        /// </summary>
        public static string ProjectOwner_Type_name_length_should_be_between_5_100_characters {
            get {
                return ResourceManager.GetString("ProjectOwner_Type_name_length_should_be_between_5_100_characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Owner Type Added Successfully.
        /// </summary>
        public static string ProjectOwnerTypeAddedSuccessfully {
            get {
                return ResourceManager.GetString("ProjectOwnerTypeAddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Occured While Adding new Project Owner Type.
        /// </summary>
        public static string ProjectOwnerTypeAddError {
            get {
                return ResourceManager.GetString("ProjectOwnerTypeAddError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to project Owner Type ID Not Available in DB.
        /// </summary>
        public static string projectOwnerTypeID_Not_Available_inDB {
            get {
                return ResourceManager.GetString("projectOwnerTypeID_Not_Available_inDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Owner Type name Already Exist!.
        /// </summary>
        public static string ProjectOwnerTypenameAlreadyExist {
            get {
                return ResourceManager.GetString("ProjectOwnerTypenameAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Project Owners Types.
        /// </summary>
        public static string SearchProjectOwnersTypes {
            get {
                return ResourceManager.GetString("SearchProjectOwnersTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Characters Not Allowed.
        /// </summary>
        public static string Special_Characters_Not_Allowed {
            get {
                return ResourceManager.GetString("Special_Characters_Not_Allowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Project Owner Type.
        /// </summary>
        public static string UpdateProjectOwnerType {
            get {
                return ResourceManager.GetString("UpdateProjectOwnerType", resourceCulture);
            }
        }
    }
}
