//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RCV {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RCV() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QA.Localization.RCV", typeof(RCV).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign.
        /// </summary>
        public static string Assign_CR {
            get {
                return ResourceManager.GetString("Assign_CR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NA.
        /// </summary>
        public static string Assign_CR_NotAllowed {
            get {
                return ResourceManager.GetString("Assign_CR_NotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned Successfully.
        /// </summary>
        public static string Assigned_Success {
            get {
                return ResourceManager.GetString("Assigned_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned RCV Retrieved Successfully .
        /// </summary>
        public static string AssignedRCVRetrievedSuccess {
            get {
                return ResourceManager.GetString("AssignedRCVRetrievedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contractor.
        /// </summary>
        public static string Contractor {
            get {
                return ResourceManager.GetString("Contractor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CR Assigned for Random Verification successfully.
        /// </summary>
        public static string CR_Assigned_RCV_Success {
            get {
                return ResourceManager.GetString("CR_Assigned_RCV_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CR Group.
        /// </summary>
        public static string CR_Group {
            get {
                return ResourceManager.GetString("CR_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CR Type.
        /// </summary>
        public static string CR_Type {
            get {
                return ResourceManager.GetString("CR_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CR ID.
        /// </summary>
        public static string CRID {
            get {
                return ResourceManager.GetString("CRID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CR Main-category.
        /// </summary>
        public static string CRMC {
            get {
                return ResourceManager.GetString("CRMC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RCV Status not available for Edit.
        /// </summary>
        public static string Edit_RCV_NotAvailable {
            get {
                return ResourceManager.GetString("Edit_RCV_NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string FeedBack_AcceptRCV {
            get {
                return ResourceManager.GetString("FeedBack_AcceptRCV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RCV Processed Successfully.
        /// </summary>
        public static string FeedBack_Action_Success {
            get {
                return ResourceManager.GetString("FeedBack_Action_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Attachments.
        /// </summary>
        public static string Feedback_AddAttached {
            get {
                return ResourceManager.GetString("Feedback_AddAttached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachments.
        /// </summary>
        public static string Feedback_AttachTable_Header {
            get {
                return ResourceManager.GetString("Feedback_AttachTable_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments: .
        /// </summary>
        public static string FeedBack_Comments {
            get {
                return ResourceManager.GetString("FeedBack_Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments Field Maximum length is 250 character.
        /// </summary>
        public static string FeedBack_Comments_LengthValidation {
            get {
                return ResourceManager.GetString("FeedBack_Comments_LengthValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CR ID: .
        /// </summary>
        public static string FeedBack_CRID {
            get {
                return ResourceManager.GetString("FeedBack_CRID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CR Registration Date: .
        /// </summary>
        public static string FeedBack_CRRegistrationDate {
            get {
                return ResourceManager.GetString("FeedBack_CRRegistrationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Feedback_Download {
            get {
                return ResourceManager.GetString("Feedback_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending On Lab Result.
        /// </summary>
        public static string FeedBack_Pending {
            get {
                return ResourceManager.GetString("FeedBack_Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project: .
        /// </summary>
        public static string FeedBack_Project {
            get {
                return ResourceManager.GetString("FeedBack_Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RCV Assign Date: .
        /// </summary>
        public static string FeedBack_RCVAssignDate {
            get {
                return ResourceManager.GetString("FeedBack_RCVAssignDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        public static string FeedBack_RejectRCV {
            get {
                return ResourceManager.GetString("FeedBack_RejectRCV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback on RCV.
        /// </summary>
        public static string FeedBack_ScreenHeader {
            get {
                return ResourceManager.GetString("FeedBack_ScreenHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        public static string FeedBack_Title {
            get {
                return ResourceManager.GetString("FeedBack_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        public static string PendingCR_Action {
            get {
                return ResourceManager.GetString("PendingCR_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NA.
        /// </summary>
        public static string PendingCR_Action_NotAllowed {
            get {
                return ResourceManager.GetString("PendingCR_Action_NotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign Date.
        /// </summary>
        public static string PendingCR_AssignDate {
            get {
                return ResourceManager.GetString("PendingCR_AssignDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned User.
        /// </summary>
        public static string PendingCR_AssignUser {
            get {
                return ResourceManager.GetString("PendingCR_AssignUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CR ID.
        /// </summary>
        public static string PendingCR_CRID {
            get {
                return ResourceManager.GetString("PendingCR_CRID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration date.
        /// </summary>
        public static string PendingCR_CRRegistration_Date {
            get {
                return ResourceManager.GetString("PendingCR_CRRegistration_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string PendingCR_Project {
            get {
                return ResourceManager.GetString("PendingCR_Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Item.
        /// </summary>
        public static string Project_Item {
            get {
                return ResourceManager.GetString("Project_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random CR.
        /// </summary>
        public static string Random_CR {
            get {
                return ResourceManager.GetString("Random_CR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration date.
        /// </summary>
        public static string Registration_Date {
            get {
                return ResourceManager.GetString("Registration_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Lab Required: .
        /// </summary>
        public static string Search_boolIsLabRequired {
            get {
                return ResourceManager.GetString("Search_boolIsLabRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CR: .
        /// </summary>
        public static string Search_CRID {
            get {
                return ResourceManager.GetString("Search_CRID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search RCV&apos;s.
        /// </summary>
        public static string Search_Head {
            get {
                return ResourceManager.GetString("Search_Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Required.
        /// </summary>
        public static string Search_IsLabReq_NotRequired {
            get {
                return ResourceManager.GetString("Search_IsLabReq_NotRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        public static string Search_IsLabReq_Required {
            get {
                return ResourceManager.GetString("Search_IsLabReq_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - Select - .
        /// </summary>
        public static string Search_IsLabReq_Select {
            get {
                return ResourceManager.GetString("Search_IsLabReq_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending CR Verification.
        /// </summary>
        public static string Search_Pending {
            get {
                return ResourceManager.GetString("Search_Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending CR Verification.
        /// </summary>
        public static string Search_Pending_Title {
            get {
                return ResourceManager.GetString("Search_Pending_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned User: .
        /// </summary>
        public static string Search_ProfileID {
            get {
                return ResourceManager.GetString("Search_ProfileID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project: .
        /// </summary>
        public static string Search_projectID {
            get {
                return ResourceManager.GetString("Search_projectID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random CR&apos;s.
        /// </summary>
        public static string Search_Random {
            get {
                return ResourceManager.GetString("Search_Random", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random CR Verification.
        /// </summary>
        public static string Search_Random_Title {
            get {
                return ResourceManager.GetString("Search_Random_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RCV Status: .
        /// </summary>
        public static string Search_Status {
            get {
                return ResourceManager.GetString("Search_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search RCV&apos;s.
        /// </summary>
        public static string Search_Title {
            get {
                return ResourceManager.GetString("Search_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign User.
        /// </summary>
        public static string SearchRes_AssignUser {
            get {
                return ResourceManager.GetString("SearchRes_AssignUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closure date.
        /// </summary>
        public static string SearchRes_ClosureDate {
            get {
                return ResourceManager.GetString("SearchRes_ClosureDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string SearchRes_Comments {
            get {
                return ResourceManager.GetString("SearchRes_Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CR.
        /// </summary>
        public static string SearchRes_CR {
            get {
                return ResourceManager.GetString("SearchRes_CR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CR Registration Date.
        /// </summary>
        public static string SearchRes_CRRegistrationDate {
            get {
                return ResourceManager.GetString("SearchRes_CRRegistrationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string SearchRes_Edit {
            get {
                return ResourceManager.GetString("SearchRes_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NA.
        /// </summary>
        public static string SearchRes_Edit_NotAllowed {
            get {
                return ResourceManager.GetString("SearchRes_Edit_NotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Required.
        /// </summary>
        public static string SearchRes_IsSampleRequired {
            get {
                return ResourceManager.GetString("SearchRes_IsSampleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string SearchRes_project {
            get {
                return ResourceManager.GetString("SearchRes_project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RCV Assign Date.
        /// </summary>
        public static string SearchRes_RCVAssignDate {
            get {
                return ResourceManager.GetString("SearchRes_RCVAssignDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string SearchRes_RCVStatus {
            get {
                return ResourceManager.GetString("SearchRes_RCVStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string SearchRes_View {
            get {
                return ResourceManager.GetString("SearchRes_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View RCV.
        /// </summary>
        public static string View_Header {
            get {
                return ResourceManager.GetString("View_Header", resourceCulture);
            }
        }
    }
}
