//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RCV_Missmatch {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RCV_Missmatch() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QA.Localization.RCV_Missmatch", typeof(RCV_Missmatch).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case Description.
        /// </summary>
        public static string Create_caseDescription {
            get {
                return ResourceManager.GetString("Create_caseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to field length between 5 - 1000 characters.
        /// </summary>
        public static string Create_caseDescription_Val_length {
            get {
                return ResourceManager.GetString("Create_caseDescription_Val_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field is mandatory.
        /// </summary>
        public static string Create_caseDescription_Val_Required {
            get {
                return ResourceManager.GetString("Create_caseDescription_Val_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments: .
        /// </summary>
        public static string Create_Comments {
            get {
                return ResourceManager.GetString("Create_Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CR: .
        /// </summary>
        public static string Create_CR {
            get {
                return ResourceManager.GetString("Create_CR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CR Registration Date: .
        /// </summary>
        public static string Create_CRRegistrationDate {
            get {
                return ResourceManager.GetString("Create_CRRegistrationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project: .
        /// </summary>
        public static string Create_Project {
            get {
                return ResourceManager.GetString("Create_Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RCV Attachments.
        /// </summary>
        public static string Create_RCV_Attachments {
            get {
                return ResourceManager.GetString("Create_RCV_Attachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RCV Assign Date: .
        /// </summary>
        public static string Create_RCVAssignDate {
            get {
                return ResourceManager.GetString("Create_RCVAssignDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RCV Details retrieved Succesfully.
        /// </summary>
        public static string Create_RetrieveRCVSuccess {
            get {
                return ResourceManager.GetString("Create_RetrieveRCVSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample 1 Details.
        /// </summary>
        public static string Create_Sample1_Header {
            get {
                return ResourceManager.GetString("Create_Sample1_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample 1 Location.
        /// </summary>
        public static string Create_Sample1_Location_Header {
            get {
                return ResourceManager.GetString("Create_Sample1_Location_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample 2 Details.
        /// </summary>
        public static string Create_Sample2_Header {
            get {
                return ResourceManager.GetString("Create_Sample2_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample 2 Location.
        /// </summary>
        public static string Create_Sample2_Location_Header {
            get {
                return ResourceManager.GetString("Create_Sample2_Location_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Missmatch Case.
        /// </summary>
        public static string Create_ScreenHeader {
            get {
                return ResourceManager.GetString("Create_ScreenHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Missmatch Case.
        /// </summary>
        public static string Create_Title {
            get {
                return ResourceManager.GetString("Create_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RCV Missmatch case not available in DB !.
        /// </summary>
        public static string Edit_ID_Not_Available_inDB {
            get {
                return ResourceManager.GetString("Edit_ID_Not_Available_inDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample1 Geographical Premises should be within Parent premises.
        /// </summary>
        public static string Map_CRSample1_Validation_Location {
            get {
                return ResourceManager.GetString("Map_CRSample1_Validation_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample2 Geographical Premises should be within Parent premises.
        /// </summary>
        public static string Map_CRSample2_Validation_Location {
            get {
                return ResourceManager.GetString("Map_CRSample2_Validation_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RCV Missmatch Case: .
        /// </summary>
        public static string RCV_Missmatch_Case {
            get {
                return ResourceManager.GetString("RCV_Missmatch_Case", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Successfully.
        /// </summary>
        public static string RCVMM_Added_Success {
            get {
                return ResourceManager.GetString("RCVMM_Added_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated Successfully.
        /// </summary>
        public static string RCVMM_Updated_Success {
            get {
                return ResourceManager.GetString("RCVMM_Updated_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RCV not valid to create Miss-match case !.
        /// </summary>
        public static string RCVNotValidMissmatch {
            get {
                return ResourceManager.GetString("RCVNotValidMissmatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to field length between 5 - 1000 characters.
        /// </summary>
        public static string Reply_ReplyMessage_Val_Length {
            get {
                return ResourceManager.GetString("Reply_ReplyMessage_Val_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field is mandatory.
        /// </summary>
        public static string Reply_ReplyMessage_Val_Required {
            get {
                return ResourceManager.GetString("Reply_ReplyMessage_Val_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field is mandatory.
        /// </summary>
        public static string Sample_Field_Required_val {
            get {
                return ResourceManager.GetString("Sample_Field_Required_val", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample maker field length between 3 - 50 digits.
        /// </summary>
        public static string Sample_Maker_Length_val {
            get {
                return ResourceManager.GetString("Sample_Maker_Length_val", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field length between 1 - 10 digits.
        /// </summary>
        public static string Sample_SizeLength_Length_val {
            get {
                return ResourceManager.GetString("Sample_SizeLength_Length_val", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select sample unit.
        /// </summary>
        public static string Sample_Unit_Required_Val {
            get {
                return ResourceManager.GetString("Sample_Unit_Required_Val", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample 1 fields are mandatory as long as any field is exist.
        /// </summary>
        public static string Sample1_Fields_Mandatory_Val {
            get {
                return ResourceManager.GetString("Sample1_Fields_Mandatory_Val", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CR: .
        /// </summary>
        public static string Search_CRID {
            get {
                return ResourceManager.GetString("Search_CRID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending On: .
        /// </summary>
        public static string Search_PendingOn {
            get {
                return ResourceManager.GetString("Search_PendingOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile: .
        /// </summary>
        public static string Search_ProfileID {
            get {
                return ResourceManager.GetString("Search_ProfileID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project: .
        /// </summary>
        public static string Search_ProjectID {
            get {
                return ResourceManager.GetString("Search_ProjectID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RCV: .
        /// </summary>
        public static string Search_RCVID {
            get {
                return ResourceManager.GetString("Search_RCVID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case Status: .
        /// </summary>
        public static string Search_RCVMM_Status {
            get {
                return ResourceManager.GetString("Search_RCVMM_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Missmatch Cases.
        /// </summary>
        public static string Search_SearchCases {
            get {
                return ResourceManager.GetString("Search_SearchCases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case Desc.
        /// </summary>
        public static string SearchRes_Case_Desc {
            get {
                return ResourceManager.GetString("SearchRes_Case_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closure date.
        /// </summary>
        public static string SearchRes_Close_Date {
            get {
                return ResourceManager.GetString("SearchRes_Close_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string SearchRes_Comments {
            get {
                return ResourceManager.GetString("SearchRes_Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversation.
        /// </summary>
        public static string SearchRes_Conversation {
            get {
                return ResourceManager.GetString("SearchRes_Conversation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CR ID.
        /// </summary>
        public static string SearchRes_CR_ID {
            get {
                return ResourceManager.GetString("SearchRes_CR_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CR Registration date.
        /// </summary>
        public static string SearchRes_CR_RegDate {
            get {
                return ResourceManager.GetString("SearchRes_CR_RegDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CR Status.
        /// </summary>
        public static string SearchRes_CR_Status {
            get {
                return ResourceManager.GetString("SearchRes_CR_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string SearchRes_Edit {
            get {
                return ResourceManager.GetString("SearchRes_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NA.
        /// </summary>
        public static string SearchRes_Edit_NA {
            get {
                return ResourceManager.GetString("SearchRes_Edit_NA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IS RCV Case.
        /// </summary>
        public static string SearchRes_Is_RCV {
            get {
                return ResourceManager.GetString("SearchRes_Is_RCV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case Maker.
        /// </summary>
        public static string SearchRes_Maker {
            get {
                return ResourceManager.GetString("SearchRes_Maker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending on.
        /// </summary>
        public static string SearchRes_PendingOn {
            get {
                return ResourceManager.GetString("SearchRes_PendingOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string SearchRes_Project {
            get {
                return ResourceManager.GetString("SearchRes_Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Item.
        /// </summary>
        public static string SearchRes_Project_Item {
            get {
                return ResourceManager.GetString("SearchRes_Project_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RCV Create Date.
        /// </summary>
        public static string SearchRes_RCV_CreateDate {
            get {
                return ResourceManager.GetString("SearchRes_RCV_CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RCV ID.
        /// </summary>
        public static string SearchRes_RCV_ID {
            get {
                return ResourceManager.GetString("SearchRes_RCV_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string SearchRes_Status {
            get {
                return ResourceManager.GetString("SearchRes_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missmatch Case details.
        /// </summary>
        public static string View_MMC_Details {
            get {
                return ResourceManager.GetString("View_MMC_Details", resourceCulture);
            }
        }
    }
}
