//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SampleTest {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SampleTest() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QA.Localization.SampleTest", typeof(SampleTest).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Sample Test.
        /// </summary>
        public static string CreateSampleTest {
            get {
                return ResourceManager.GetString("CreateSampleTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description: *.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description length should be between 2 - 250 characters.
        /// </summary>
        public static string Description_length_validation {
            get {
                return ResourceManager.GetString("Description_length_validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description: .
        /// </summary>
        public static string Description_Search {
            get {
                return ResourceManager.GetString("Description_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to description.
        /// </summary>
        public static string description_ViewSearch {
            get {
                return ResourceManager.GetString("description_ViewSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample test: .
        /// </summary>
        public static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample test name: *.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name length should be between 5 - 100 characters.
        /// </summary>
        public static string name_length_validation {
            get {
                return ResourceManager.GetString("name_length_validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample test name: .
        /// </summary>
        public static string Name_Search {
            get {
                return ResourceManager.GetString("Name_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name.
        /// </summary>
        public static string name_ViewSearch {
            get {
                return ResourceManager.GetString("name_ViewSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name already exist !.
        /// </summary>
        public static string NameAlreadyExist {
            get {
                return ResourceManager.GetString("NameAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Sample test Category .
        /// </summary>
        public static string provide_avalid_CategoryID {
            get {
                return ResourceManager.GetString("provide_avalid_CategoryID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to plesae provide a valid description.
        /// </summary>
        public static string Provide_Description_Validation {
            get {
                return ResourceManager.GetString("Provide_Description_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a valid name !.
        /// </summary>
        public static string provide_valid_Name {
            get {
                return ResourceManager.GetString("provide_valid_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Test Added Successfully.
        /// </summary>
        public static string SampleTestAddedSuccessfully {
            get {
                return ResourceManager.GetString("SampleTestAddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample test Category: *.
        /// </summary>
        public static string SampleTestCategoryID {
            get {
                return ResourceManager.GetString("SampleTestCategoryID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample test Category: .
        /// </summary>
        public static string SampleTestCategoryID_Search {
            get {
                return ResourceManager.GetString("SampleTestCategoryID_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample test Category.
        /// </summary>
        public static string SampleTestCategoryID_ViewSearch {
            get {
                return ResourceManager.GetString("SampleTestCategoryID_ViewSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Test Details.
        /// </summary>
        public static string SampleTestDetails {
            get {
                return ResourceManager.GetString("SampleTestDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sample test Not Available in DB.
        /// </summary>
        public static string sampleTestID_Not_Available_inDB {
            get {
                return ResourceManager.GetString("sampleTestID_Not_Available_inDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Test Search.
        /// </summary>
        public static string SampleTestID_Search {
            get {
                return ResourceManager.GetString("SampleTestID_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Test.
        /// </summary>
        public static string SampleTestID_ViewSearch {
            get {
                return ResourceManager.GetString("SampleTestID_ViewSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Sample Test.
        /// </summary>
        public static string SearchSampleTest {
            get {
                return ResourceManager.GetString("SearchSampleTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Sample Test.
        /// </summary>
        public static string UpdateSampleTest {
            get {
                return ResourceManager.GetString("UpdateSampleTest", resourceCulture);
            }
        }
    }
}
