//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SampleType {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SampleType() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QA.Localization.SampleType", typeof(SampleType).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Sample Test Category.
        /// </summary>
        public static string Create_Sample_Type {
            get {
                return ResourceManager.GetString("Create_Sample_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Test Category description length should be between 2 - 250 characters.
        /// </summary>
        public static string Desc_length_validation {
            get {
                return ResourceManager.GetString("Desc_length_validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description: *.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        public static string Description_Search {
            get {
                return ResourceManager.GetString("Description_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to description.
        /// </summary>
        public static string description_ViewSearch {
            get {
                return ResourceManager.GetString("description_ViewSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Test Category ID.
        /// </summary>
        public static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Test Category name: *.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Test Category name length should be between 5 - 100 characters.
        /// </summary>
        public static string Name_length_Validation {
            get {
                return ResourceManager.GetString("Name_length_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Test Category name: .
        /// </summary>
        public static string Name_Search {
            get {
                return ResourceManager.GetString("Name_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name.
        /// </summary>
        public static string name_ViewSearch {
            get {
                return ResourceManager.GetString("name_ViewSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Test Category name Already Exist !.
        /// </summary>
        public static string NameAlreadyExist {
            get {
                return ResourceManager.GetString("NameAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please provide a valid Sample Test Category Description.
        /// </summary>
        public static string provide_valid_Description {
            get {
                return ResourceManager.GetString("provide_valid_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please provide a valid Sample Test Category Name.
        /// </summary>
        public static string provide_valid_Name {
            get {
                return ResourceManager.GetString("provide_valid_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Test Category Details.
        /// </summary>
        public static string Sample_Type_Details {
            get {
                return ResourceManager.GetString("Sample_Type_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Test Category Added Successfully.
        /// </summary>
        public static string SampleTypeAddedSuccessfully {
            get {
                return ResourceManager.GetString("SampleTypeAddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Occured While Adding new Sample Test Category.
        /// </summary>
        public static string SampleTypeAddError {
            get {
                return ResourceManager.GetString("SampleTypeAddError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sample Test Category ID Not Available in DB.
        /// </summary>
        public static string sampleTypeID_Not_Available_inDB {
            get {
                return ResourceManager.GetString("sampleTypeID_Not_Available_inDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Test Category Search.
        /// </summary>
        public static string SampleTypeID_ViewSearch {
            get {
                return ResourceManager.GetString("SampleTypeID_ViewSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Sample Test Category.
        /// </summary>
        public static string SearchSampleType {
            get {
                return ResourceManager.GetString("SearchSampleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Sample Test Category.
        /// </summary>
        public static string UpdateSampleType1 {
            get {
                return ResourceManager.GetString("UpdateSampleType1", resourceCulture);
            }
        }
    }
}
