//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UserProfile {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserProfile() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QA.Localization.UserProfile", typeof(UserProfile).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Assistant User.
        /// </summary>
        public static string boolIsAssistant {
            get {
                return ResourceManager.GetString("boolIsAssistant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Assistant User.
        /// </summary>
        public static string boolIsAssistant_ViewSearch {
            get {
                return ResourceManager.GetString("boolIsAssistant_ViewSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Locked: .
        /// </summary>
        public static string boolIsLocked {
            get {
                return ResourceManager.GetString("boolIsLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Locked.
        /// </summary>
        public static string boolIsLocked_ViewSearch {
            get {
                return ResourceManager.GetString("boolIsLocked_ViewSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create User Profile.
        /// </summary>
        public static string CreateUserProfile {
            get {
                return ResourceManager.GetString("CreateUserProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saudi Citizens.
        /// </summary>
        public static string DDL_NatTypes_NID {
            get {
                return ResourceManager.GetString("DDL_NatTypes_NID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees.
        /// </summary>
        public static string DDL_NatTypes_VisitorID {
            get {
                return ResourceManager.GetString("DDL_NatTypes_VisitorID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee ID should be between 5 - 20 characters.
        /// </summary>
        public static string EmpID_length_validation {
            get {
                return ResourceManager.GetString("EmpID_length_validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee ID: .
        /// </summary>
        public static string employeeId {
            get {
                return ResourceManager.GetString("employeeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee ID: .
        /// </summary>
        public static string employeeId_Search {
            get {
                return ResourceManager.GetString("employeeId_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee ID.
        /// </summary>
        public static string employeeId_ViewSearch {
            get {
                return ResourceManager.GetString("employeeId_ViewSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee ID Already Exist !.
        /// </summary>
        public static string EmployeeIDAlreadyExist {
            get {
                return ResourceManager.GetString("EmployeeIDAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Name: *.
        /// </summary>
        public static string EmployeeName {
            get {
                return ResourceManager.GetString("EmployeeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee name length should be between 5 - 50 characters.
        /// </summary>
        public static string EmployeeName_length_Validation {
            get {
                return ResourceManager.GetString("EmployeeName_length_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Name: .
        /// </summary>
        public static string employeeName_Search {
            get {
                return ResourceManager.GetString("employeeName_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Name.
        /// </summary>
        public static string EmployeeName_ViewSearch {
            get {
                return ResourceManager.GetString("EmployeeName_ViewSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to expiry date.
        /// </summary>
        public static string expiry_ViewSearch {
            get {
                return ResourceManager.GetString("expiry_ViewSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiry Date: .
        /// </summary>
        public static string ExpiryDate {
            get {
                return ResourceManager.GetString("ExpiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiry Date.
        /// </summary>
        public static string ExpiryDate_ViewSearch {
            get {
                return ResourceManager.GetString("ExpiryDate_ViewSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Project Owner Member.
        /// </summary>
        public static string isProjectOwnerMember {
            get {
                return ResourceManager.GetString("isProjectOwnerMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name: .
        /// </summary>
        public static string name_Search {
            get {
                return ResourceManager.GetString("name_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name.
        /// </summary>
        public static string name_ViewSearch {
            get {
                return ResourceManager.GetString("name_ViewSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National ID: *.
        /// </summary>
        public static string NationalId {
            get {
                return ResourceManager.GetString("NationalId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National ID: .
        /// </summary>
        public static string NationalId_Search {
            get {
                return ResourceManager.GetString("NationalId_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National ID.
        /// </summary>
        public static string NationalId_ViewSearch {
            get {
                return ResourceManager.GetString("NationalId_ViewSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationality: *.
        /// </summary>
        public static string nationalityID {
            get {
                return ResourceManager.GetString("nationalityID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationality: .
        /// </summary>
        public static string nationalityID_Search {
            get {
                return ResourceManager.GetString("nationalityID_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationality.
        /// </summary>
        public static string nationalityID_ViewSearch {
            get {
                return ResourceManager.GetString("nationalityID_ViewSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationality Type: *.
        /// </summary>
        public static string nationalityTypeID {
            get {
                return ResourceManager.GetString("nationalityTypeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationality Type: .
        /// </summary>
        public static string nationalityTypeID_Search {
            get {
                return ResourceManager.GetString("nationalityTypeID_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationality Type.
        /// </summary>
        public static string nationalityTypeID_ViewSearch {
            get {
                return ResourceManager.GetString("nationalityTypeID_ViewSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National ID should be between 5 - 20 characters.
        /// </summary>
        public static string NID_length_Validation {
            get {
                return ResourceManager.GetString("NID_length_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National ID Already Exist !.
        /// </summary>
        public static string NIDAlreadyExist {
            get {
                return ResourceManager.GetString("NIDAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password: *.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password length should be between 5 - 30 characters.
        /// </summary>
        public static string Password_length_Validation {
            get {
                return ResourceManager.GetString("Password_length_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please provide a valid ExpiryDate.
        /// </summary>
        public static string please_provide_avalid_ExpiryDate {
            get {
                return ResourceManager.GetString("please_provide_avalid_ExpiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please provide a valid Password.
        /// </summary>
        public static string please_provide_avalid_Password {
            get {
                return ResourceManager.GetString("please_provide_avalid_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please provide a valid User Name.
        /// </summary>
        public static string please_provide_avalid_UserName {
            get {
                return ResourceManager.GetString("please_provide_avalid_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Owner: .
        /// </summary>
        public static string projectOwnerID {
            get {
                return ResourceManager.GetString("projectOwnerID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Owner.
        /// </summary>
        public static string projectOwnerID_ViewSearch {
            get {
                return ResourceManager.GetString("projectOwnerID_ViewSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please provide a valid Employee ID: .
        /// </summary>
        public static string provide_avalid_EmpID {
            get {
                return ResourceManager.GetString("provide_avalid_EmpID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please provide a valid National ID.
        /// </summary>
        public static string provide_avalid_NID {
            get {
                return ResourceManager.GetString("provide_avalid_NID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please Select Nationality.
        /// </summary>
        public static string provide_avalid_NityID {
            get {
                return ResourceManager.GetString("provide_avalid_NityID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Nationality type.
        /// </summary>
        public static string provide_avalid_Ntype {
            get {
                return ResourceManager.GetString("provide_avalid_Ntype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select User Role.
        /// </summary>
        public static string Provide_valid_RoleID {
            get {
                return ResourceManager.GetString("Provide_valid_RoleID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select User type.
        /// </summary>
        public static string provide_valid_Usertype {
            get {
                return ResourceManager.GetString("provide_valid_Usertype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Super User ID: .
        /// </summary>
        public static string superUserID {
            get {
                return ResourceManager.GetString("superUserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Super User:.
        /// </summary>
        public static string SuperUserID_Search {
            get {
                return ResourceManager.GetString("SuperUserID_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Super User.
        /// </summary>
        public static string superUserID_ViewSearch {
            get {
                return ResourceManager.GetString("superUserID_ViewSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update User Profile.
        /// </summary>
        public static string UpdateUserProfile {
            get {
                return ResourceManager.GetString("UpdateUserProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name: *.
        /// </summary>
        public static string User_name {
            get {
                return ResourceManager.GetString("User_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string User_name_ViewSearch {
            get {
                return ResourceManager.GetString("User_name_ViewSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID: .
        /// </summary>
        public static string UserID {
            get {
                return ResourceManager.GetString("UserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user ID.
        /// </summary>
        public static string userID_ViewSearch {
            get {
                return ResourceManager.GetString("userID_ViewSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID: .
        /// </summary>
        public static string UserIDSearch {
            get {
                return ResourceManager.GetString("UserIDSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name length should be between 5 - 30 characters.
        /// </summary>
        public static string Username_length_Validation {
            get {
                return ResourceManager.GetString("Username_length_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name: .
        /// </summary>
        public static string userName_Search {
            get {
                return ResourceManager.GetString("userName_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name Already Exist !.
        /// </summary>
        public static string UsernameAlreadyExist {
            get {
                return ResourceManager.GetString("UsernameAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Profile Added Successfully.
        /// </summary>
        public static string UserProfileAddedSuccessfully {
            get {
                return ResourceManager.GetString("UserProfileAddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Profile Details.
        /// </summary>
        public static string UserProfileDetails {
            get {
                return ResourceManager.GetString("UserProfileDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Profile ID Not Available in DB.
        /// </summary>
        public static string UserProfileID_Not_Available_inDB {
            get {
                return ResourceManager.GetString("UserProfileID_Not_Available_inDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Role: *.
        /// </summary>
        public static string UserRole {
            get {
                return ResourceManager.GetString("UserRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Role.
        /// </summary>
        public static string UserRole_ViewSearch {
            get {
                return ResourceManager.GetString("UserRole_ViewSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Type: *.
        /// </summary>
        public static string UserTypeID {
            get {
                return ResourceManager.GetString("UserTypeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Type: .
        /// </summary>
        public static string UserTypeID_Search {
            get {
                return ResourceManager.GetString("UserTypeID_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Type.
        /// </summary>
        public static string UserTypeID_ViewSearch {
            get {
                return ResourceManager.GetString("UserTypeID_ViewSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please Select Project Owner.
        /// </summary>
        public static string valid_projectOwner {
            get {
                return ResourceManager.GetString("valid_projectOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please Select Super-User.
        /// </summary>
        public static string valid_SuperID {
            get {
                return ResourceManager.GetString("valid_SuperID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Details.
        /// </summary>
        public static string Wizard_ContactDetails {
            get {
                return ResourceManager.GetString("Wizard_ContactDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Details.
        /// </summary>
        public static string Wizard_LoginDetails {
            get {
                return ResourceManager.GetString("Wizard_LoginDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Details.
        /// </summary>
        public static string Wizard_UserDetails {
            get {
                return ResourceManager.GetString("Wizard_UserDetails", resourceCulture);
            }
        }
    }
}
