//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UserRoles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserRoles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QA.Localization.UserRoles", typeof(UserRoles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Role.
        /// </summary>
        public static string CreateRole {
            get {
                return ResourceManager.GetString("CreateRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial Screen: *.
        /// </summary>
        public static string initialScreenID {
            get {
                return ResourceManager.GetString("initialScreenID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial Screen: .
        /// </summary>
        public static string initialScreenID_Search {
            get {
                return ResourceManager.GetString("initialScreenID_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial Screen.
        /// </summary>
        public static string initialScreenID_ViewSearch {
            get {
                return ResourceManager.GetString("initialScreenID_ViewSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role name field length between 5 - 100 characters.
        /// </summary>
        public static string Name_length_validation {
            get {
                return ResourceManager.GetString("Name_length_validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role-Name: .
        /// </summary>
        public static string name_Search {
            get {
                return ResourceManager.GetString("name_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role-name already exist !.
        /// </summary>
        public static string NameAlreadyExist {
            get {
                return ResourceManager.GetString("NameAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select initial screen.
        /// </summary>
        public static string provide_avalid_initialScreenID {
            get {
                return ResourceManager.GetString("provide_avalid_initialScreenID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a valid role name .
        /// </summary>
        public static string provide_valid_Name {
            get {
                return ResourceManager.GetString("provide_valid_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role-Name: *.
        /// </summary>
        public static string Role_Name {
            get {
                return ResourceManager.GetString("Role_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role-Name: .
        /// </summary>
        public static string Role_Name_Search {
            get {
                return ResourceManager.GetString("Role_Name_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role-Name.
        /// </summary>
        public static string Role_Name_ViewSearch {
            get {
                return ResourceManager.GetString("Role_Name_ViewSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Details.
        /// </summary>
        public static string RoleDetails {
            get {
                return ResourceManager.GetString("RoleDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Not Available in the DB.
        /// </summary>
        public static string RoleID_Not_Available_inDB {
            get {
                return ResourceManager.GetString("RoleID_Not_Available_inDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Roles.
        /// </summary>
        public static string SearchRoles {
            get {
                return ResourceManager.GetString("SearchRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Role.
        /// </summary>
        public static string UpdateRole {
            get {
                return ResourceManager.GetString("UpdateRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checker.
        /// </summary>
        public static string UR_Action_CLWF_Checker {
            get {
                return ResourceManager.GetString("UR_Action_CLWF_Checker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maker.
        /// </summary>
        public static string UR_Action_CLWF_Maker {
            get {
                return ResourceManager.GetString("UR_Action_CLWF_Maker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string UR_Action_CR_Action {
            get {
                return ResourceManager.GetString("UR_Action_CR_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add attachment.
        /// </summary>
        public static string UR_Action_CR_AddAttach {
            get {
                return ResourceManager.GetString("UR_Action_CR_AddAttach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View attachment.
        /// </summary>
        public static string UR_Action_CR_ViewAttach {
            get {
                return ResourceManager.GetString("UR_Action_CR_ViewAttach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string UR_Action_Create {
            get {
                return ResourceManager.GetString("UR_Action_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contractor.
        /// </summary>
        public static string UR_Action_Dashboard_Contractor {
            get {
                return ResourceManager.GetString("UR_Action_Dashboard_Contractor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string UR_Action_Edit {
            get {
                return ResourceManager.GetString("UR_Action_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute.
        /// </summary>
        public static string UR_Action_RCV_Action {
            get {
                return ResourceManager.GetString("UR_Action_RCV_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random Search.
        /// </summary>
        public static string UR_Action_RCV_RandomSearch {
            get {
                return ResourceManager.GetString("UR_Action_RCV_RandomSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Case.
        /// </summary>
        public static string UR_Action_RCVMMConv_Close {
            get {
                return ResourceManager.GetString("UR_Action_RCVMMConv_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escalation.
        /// </summary>
        public static string UR_Action_RCVMMConv_Escalation {
            get {
                return ResourceManager.GetString("UR_Action_RCVMMConv_Escalation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Reply.
        /// </summary>
        public static string UR_Action_RCVMMConv_Reply {
            get {
                return ResourceManager.GetString("UR_Action_RCVMMConv_Reply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string UR_Action_RCVMMConv_View {
            get {
                return ResourceManager.GetString("UR_Action_RCVMMConv_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string UR_Action_Search {
            get {
                return ResourceManager.GetString("UR_Action_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string UR_Action_View {
            get {
                return ResourceManager.GetString("UR_Action_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check-List Item.
        /// </summary>
        public static string UR_CheckListItem_Head {
            get {
                return ResourceManager.GetString("UR_CheckListItem_Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check-List Group.
        /// </summary>
        public static string UR_CheckListItemGroup_Head {
            get {
                return ResourceManager.GetString("UR_CheckListItemGroup_Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check-Lists.
        /// </summary>
        public static string UR_CheckLists_Head {
            get {
                return ResourceManager.GetString("UR_CheckLists_Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check-list Work flow.
        /// </summary>
        public static string UR_CLWF_Head {
            get {
                return ResourceManager.GetString("UR_CLWF_Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to check-list flow sequence.
        /// </summary>
        public static string UR_CLWF_Sequence_Head {
            get {
                return ResourceManager.GetString("UR_CLWF_Sequence_Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complaint.
        /// </summary>
        public static string UR_Complaint_Head {
            get {
                return ResourceManager.GetString("UR_Complaint_Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CR.
        /// </summary>
        public static string UR_CR_Head {
            get {
                return ResourceManager.GetString("UR_CR_Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CR Reports.
        /// </summary>
        public static string UR_CR_Reports_Head {
            get {
                return ResourceManager.GetString("UR_CR_Reports_Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CR Type.
        /// </summary>
        public static string UR_CRType_Head {
            get {
                return ResourceManager.GetString("UR_CRType_Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CR Type Group.
        /// </summary>
        public static string UR_CRTypeGroup_Head {
            get {
                return ResourceManager.GetString("UR_CRTypeGroup_Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CR Type category.
        /// </summary>
        public static string UR_CRTYPEMC_Head {
            get {
                return ResourceManager.GetString("UR_CRTYPEMC_Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorized Lab..
        /// </summary>
        public static string UR_Dashboard_AuthLab {
            get {
                return ResourceManager.GetString("UR_Dashboard_AuthLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CEO.
        /// </summary>
        public static string UR_Dashboard_CEO {
            get {
                return ResourceManager.GetString("UR_Dashboard_CEO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultant Engineer.
        /// </summary>
        public static string UR_Dashboard_ConsultantEng {
            get {
                return ResourceManager.GetString("UR_Dashboard_ConsultantEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string UR_Dashboard_Head {
            get {
                return ResourceManager.GetString("UR_Dashboard_Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality Engineer.
        /// </summary>
        public static string UR_Dashboard_QualityEng {
            get {
                return ResourceManager.GetString("UR_Dashboard_QualityEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supervisor Engineer.
        /// </summary>
        public static string UR_Dashboard_SuperEng {
            get {
                return ResourceManager.GetString("UR_Dashboard_SuperEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technician.
        /// </summary>
        public static string UR_Dashboard_Technician {
            get {
                return ResourceManager.GetString("UR_Dashboard_Technician", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string UR_Department_Head {
            get {
                return ResourceManager.GetString("UR_Department_Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Section.
        /// </summary>
        public static string UR_DepartmentSection_Head {
            get {
                return ResourceManager.GetString("UR_DepartmentSection_Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factory.
        /// </summary>
        public static string UR_Factory_Head {
            get {
                return ResourceManager.GetString("UR_Factory_Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factory Type.
        /// </summary>
        public static string UR_FactoryType_Head {
            get {
                return ResourceManager.GetString("UR_FactoryType_Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mixer.
        /// </summary>
        public static string UR_Mixer_Head {
            get {
                return ResourceManager.GetString("UR_Mixer_Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mixer Type.
        /// </summary>
        public static string UR_MixerType_Head {
            get {
                return ResourceManager.GetString("UR_MixerType_Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string UR_Project_Head {
            get {
                return ResourceManager.GetString("UR_Project_Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Reports.
        /// </summary>
        public static string UR_Project_Reports_Head {
            get {
                return ResourceManager.GetString("UR_Project_Reports_Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Owner.
        /// </summary>
        public static string UR_ProjectOwner_Head {
            get {
                return ResourceManager.GetString("UR_ProjectOwner_Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Owner Type.
        /// </summary>
        public static string UR_ProjectOwnerType_Head {
            get {
                return ResourceManager.GetString("UR_ProjectOwnerType_Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random CR Verification.
        /// </summary>
        public static string UR_RCV_Head {
            get {
                return ResourceManager.GetString("UR_RCV_Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RCV Miss-match Workflow.
        /// </summary>
        public static string UR_RCVMM_Conversation_Head {
            get {
                return ResourceManager.GetString("UR_RCVMM_Conversation_Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RCV Miss-match.
        /// </summary>
        public static string UR_RCVMM_Head {
            get {
                return ResourceManager.GetString("UR_RCVMM_Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CR Projects Search.
        /// </summary>
        public static string UR_Reports_CR_Projects_Search {
            get {
                return ResourceManager.GetString("UR_Reports_CR_Projects_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CR Samples Search.
        /// </summary>
        public static string UR_Reports_CR_Samples_Search {
            get {
                return ResourceManager.GetString("UR_Reports_CR_Samples_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CR Samples Search Detailed.
        /// </summary>
        public static string UR_Reports_CR_Samples_SearchDetailed {
            get {
                return ResourceManager.GetString("UR_Reports_CR_Samples_SearchDetailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CR Search.
        /// </summary>
        public static string UR_Reports_CR_Search {
            get {
                return ResourceManager.GetString("UR_Reports_CR_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CR View.
        /// </summary>
        public static string UR_Reports_CR_View {
            get {
                return ResourceManager.GetString("UR_Reports_CR_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports View.
        /// </summary>
        public static string UR_Reports_Project_View {
            get {
                return ResourceManager.GetString("UR_Reports_Project_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Test.
        /// </summary>
        public static string UR_SampleTest_Head {
            get {
                return ResourceManager.GetString("UR_SampleTest_Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Test Category.
        /// </summary>
        public static string UR_SampleTestCategory_Head {
            get {
                return ResourceManager.GetString("UR_SampleTestCategory_Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Profile.
        /// </summary>
        public static string UR_UserProfile_Head {
            get {
                return ResourceManager.GetString("UR_UserProfile_Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Roles.
        /// </summary>
        public static string UR_UserRoles_Head {
            get {
                return ResourceManager.GetString("UR_UserRoles_Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User-Role Added Successfully.
        /// </summary>
        public static string UserRoleAddedSuccessfully {
            get {
                return ResourceManager.GetString("UserRoleAddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Roles.
        /// </summary>
        public static string UserRolesSection {
            get {
                return ResourceManager.GetString("UserRolesSection", resourceCulture);
            }
        }
    }
}
