//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHECKLIST_FLOW
    {
        public int CL_FLOW_SEQ { get; set; }
        public Nullable<int> CL_FLOW_ID { get; set; }
        public Nullable<int> CL_ID { get; set; }
        public Nullable<int> CL_GROUP_ID { get; set; }
        public Nullable<int> CL_ITEM_ID { get; set; }
        public bool AVAILABLE_ITEM { get; set; }
        public string COMMENTS { get; set; }
        public Nullable<int> ATTACHMENT_ID { get; set; }
    }
}
