//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHECKLIST_FLOW_MASTER
    {
        public int ID { get; set; }
        public Nullable<int> CHECKLISTID { get; set; }
        public string CL_PARTY { get; set; }
        public Nullable<int> CL_SEQUENCEID { get; set; }
        public Nullable<int> TECHNICIANID { get; set; }
        public Nullable<int> TECHNICIAN_MAXDAYS { get; set; }
        public string TECHNICIAN_ACTION { get; set; }
        public Nullable<System.DateTime> TECHNICIAN_ACTION_DATE { get; set; }
        public Nullable<int> SUPERVISORENGID { get; set; }
        public Nullable<int> SUPERENG_MAXDAYS { get; set; }
        public string SUPERENG_ACTION { get; set; }
        public Nullable<System.DateTime> SUPERENG_ACTION_DATE { get; set; }
        public Nullable<int> QALABID { get; set; }
        public Nullable<int> QALAB_MAXDAYS { get; set; }
        public string QALAB_ACTION { get; set; }
        public Nullable<System.DateTime> QALAB_ACTION_DATE { get; set; }
        public Nullable<int> REPRESENTITIVESUPERID { get; set; }
        public Nullable<int> REPSUPER_MAXDAYS { get; set; }
        public string RS_ACTION { get; set; }
        public Nullable<System.DateTime> RS_ACTION_DATE { get; set; }
        public Nullable<System.DateTime> REGISTRATIONDATE { get; set; }
        public Nullable<int> STATUS { get; set; }
        public Nullable<System.DateTime> CLOSURENDATE { get; set; }
        public Nullable<int> MAKERID { get; set; }
    }
}
