//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPLAINT
    {
        public int COMPLAINTS_ID { get; set; }
        public Nullable<int> CR_ID { get; set; }
        public string COMMENTS { get; set; }
        public string DESCRIPTION { get; set; }
        public string NOTIFICATION_LIST { get; set; }
        public Nullable<int> ATTACHMENT_ID { get; set; }
        public Nullable<int> COMPLAINT_STATUS { get; set; }
        public string MAKER { get; set; }
        public Nullable<System.DateTime> MAKER_DAT_TIM { get; set; }
    }
}
