//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTACT_ID
    {
        public int CONTACT_ID1 { get; set; }
        public string PHONE_int { get; set; }
        public string WORK_PHONE_NUBER { get; set; }
        public string WORK_EXTENTION { get; set; }
        public string MOBILE_int { get; set; }
        public string EMAIL { get; set; }
        public string FAX { get; set; }
        public string ADDRESS { get; set; }
        public string WORK_PLACE { get; set; }
    }
}
