//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CR
    {
        public int CR_ID { get; set; }
        public Nullable<int> PROJECT_ID { get; set; }
        public Nullable<int> PROJECT_ITEM_ID { get; set; }
        public Nullable<System.DateTime> REGISTER_DATE { get; set; }
        public Nullable<int> CR_TYPE_ID { get; set; }
        public Nullable<int> FLOW_ID { get; set; }
        public Nullable<int> STATUS { get; set; }
        public Nullable<int> SAMPLE_ID { get; set; }
        public Nullable<System.DateTime> CLOSURE_DATE { get; set; }
        public Nullable<int> MAP_SELECTION_ID { get; set; }
        public string MAKER { get; set; }
    }
}
