//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CR_STATUSES
    {
        public int STATUS_SEQ_ID { get; set; }
        public string STATUS_ENG_DESC { get; set; }
        public string STATUS_ARA_DESC { get; set; }
        public bool IS_ACTIVE { get; set; }
    }
}
