//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CR_TYPES_FLOW
    {
        public int CRTF_ID { get; set; }
        public string CRTF_NAME { get; set; }
        public bool IS_SUPERVISOR_ENG { get; set; }
        public string SUPERVISOR_ENG_PERIOD { get; set; }
        public Nullable<bool> IS_CONSULTANT { get; set; }
        public string CONSULTANT_PERION { get; set; }
        public bool IS_LAB { get; set; }
        public string LAB_PERIOD { get; set; }
        public bool IS_ACTIVE { get; set; }
        public string MAKER { get; set; }
    }
}
