//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEPARTMENT
    {
        public int DEPARTMENT_ID { get; set; }
        public Nullable<int> PROJECT_OWNER_ID { get; set; }
        public string NAME { get; set; }
        public string DESCREPTION { get; set; }
        public Nullable<bool> IS_ACTIVE { get; set; }
        public string MAKER { get; set; }
        public Nullable<System.DateTime> MAKER_DAT_TIM { get; set; }
    }
}
