//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOG_MESSAGES
    {
        public int IDSEQUENCE { get; set; }
        public string USERID { get; set; }
        public string FUNCTIONNAME { get; set; }
        public Nullable<System.DateTime> DATETIME { get; set; }
        public string INPUTPARAMETERS { get; set; }
        public string OUTPUTPARAMETERS { get; set; }
        public Nullable<bool> STATUS { get; set; }
    }
}
