//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAP_SELECTIONS
    {
        public int MAP_SELECTION_ID { get; set; }
        public Nullable<int> ZOOM_LEVEL { get; set; }
        public string CENTER_LAT { get; set; }
        public string CENTER_LONG { get; set; }
        public string SELECTION_TYPE { get; set; }
        public string CIRCLE_DIAMETER { get; set; }
        public string GEOMETRY_SHAPE { get; set; }
    }
}
