//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MIXER
    {
        public int MIXER_ID { get; set; }
        public Nullable<int> TYPE_ID { get; set; }
        public Nullable<int> FACTORY_ID { get; set; }
        public string MIXER_CODE { get; set; }
        public string MIXER_MODEL { get; set; }
        public string NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public string MIXER_STATUS { get; set; }
        public string MIXER_POWER { get; set; }
        public bool IS_ACTIVE { get; set; }
        public string MAKER { get; set; }
        public Nullable<System.DateTime> MAKER_DAT_TIME { get; set; }
    }
}
