//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QA.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QualityDbEntities : DbContext
    {
        public QualityDbEntities()
            : base("name=QualityDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<APP_CONFIG> APP_CONFIG { get; set; }
        public DbSet<ATTACHMENT> ATTACHMENTS { get; set; }
        public DbSet<CHECK_LIST> CHECK_LIST { get; set; }
        public DbSet<CHECK_LIST_GROUPS> CHECK_LIST_GROUPS { get; set; }
        public DbSet<CHECKLIST_FLOW> CHECKLIST_FLOW { get; set; }
        public DbSet<CHECKLIST_FLOW_MASTER> CHECKLIST_FLOW_MASTER { get; set; }
        public DbSet<CHECKLIST_FLOW_SEQUENCE> CHECKLIST_FLOW_SEQUENCE { get; set; }
        public DbSet<CL_FLOW_STATUSES> CL_FLOW_STATUSES { get; set; }
        public DbSet<CL_GROUPS_ITEMS> CL_GROUPS_ITEMS { get; set; }
        public DbSet<COMPLAINT> COMPLAINTS { get; set; }
        public DbSet<CONTACT_ID> CONTACT_ID { get; set; }
        public DbSet<COUNTRy> COUNTRIES { get; set; }
        public DbSet<CR_FLOW> CR_FLOW { get; set; }
        public DbSet<CR_STATUSES> CR_STATUSES { get; set; }
        public DbSet<CR_TYPE_GROUPS> CR_TYPE_GROUPS { get; set; }
        public DbSet<CR_TYPES> CR_TYPES { get; set; }
        public DbSet<CR_TYPES_FLOW> CR_TYPES_FLOW { get; set; }
        public DbSet<CR_TYPES_MAIN_CATEGORIES> CR_TYPES_MAIN_CATEGORIES { get; set; }
        public DbSet<DEPARTMENT> DEPARTMENTs { get; set; }
        public DbSet<DEPARTMENT_SECTION> DEPARTMENT_SECTION { get; set; }
        public DbSet<FACTORY> FACTORies { get; set; }
        public DbSet<FACTORY_TYPES> FACTORY_TYPES { get; set; }
        public DbSet<LOG_MESSAGES> LOG_MESSAGES { get; set; }
        public DbSet<LT_INITIALSCREENS> LT_INITIALSCREENS { get; set; }
        public DbSet<LT_MEASURE_UNITS> LT_MEASURE_UNITS { get; set; }
        public DbSet<MAP_POINTS> MAP_POINTS { get; set; }
        public DbSet<MIXER> MIXERs { get; set; }
        public DbSet<MIXER_TYPES> MIXER_TYPES { get; set; }
        public DbSet<NAIONAL_TYPE> NAIONAL_TYPE { get; set; }
        public DbSet<NATIONALITY> NATIONALITies { get; set; }
        public DbSet<NOTE> NOTES { get; set; }
        public DbSet<PROJECT_OWNER> PROJECT_OWNER { get; set; }
        public DbSet<PROJECT_OWNER_TYPE> PROJECT_OWNER_TYPE { get; set; }
        public DbSet<PROJECT> PROJECTS { get; set; }
        public DbSet<RCV_STATUS_LOV> RCV_STATUS_LOV { get; set; }
        public DbSet<RCVMM_ASSIGNED_LOV> RCVMM_ASSIGNED_LOV { get; set; }
        public DbSet<RCVMM_STATUS_LOV> RCVMM_STATUS_LOV { get; set; }
        public DbSet<SAMPLE_TEST> SAMPLE_TEST { get; set; }
        public DbSet<SAMPLE_TEST_CATEGORIES> SAMPLE_TEST_CATEGORIES { get; set; }
        public DbSet<SAMPLE_TYPE> SAMPLE_TYPE { get; set; }
        public DbSet<SAMPLE> SAMPLES { get; set; }
        public DbSet<SUPER_USERS> SUPER_USERS { get; set; }
        public DbSet<TEST_SPATIAL_DATA> TEST_SPATIAL_DATA { get; set; }
        public DbSet<USER_PROFILE_TYPE> USER_PROFILE_TYPE { get; set; }
        public DbSet<USER_ROLES> USER_ROLES { get; set; }
        public DbSet<USERS_LOGIN> USERS_LOGIN { get; set; }
        public DbSet<USERS_PROFILE> USERS_PROFILE { get; set; }
        public DbSet<CR> CRs { get; set; }
        public DbSet<MAP_SELECTIONS> MAP_SELECTIONS { get; set; }
        public DbSet<PROJECT_ITEMS> PROJECT_ITEMS { get; set; }
    }
}
