//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROJECT
    {
        public int PROJECTS_ID { get; set; }
        public string NAME { get; set; }
        public Nullable<int> PROJECT_OWNER_ID { get; set; }
        public Nullable<int> SUPERVISOR_ENG_ID { get; set; }
        public Nullable<int> SECTION_ID { get; set; }
        public Nullable<int> CONSULTANT_ID { get; set; }
        public Nullable<int> CONSULANT_ASSIST_ID { get; set; }
        public Nullable<int> CONTRACTOR_ID { get; set; }
        public Nullable<int> CONTRACTOR_ASSIST_ID { get; set; }
        public Nullable<int> AUTH_LAB_ID { get; set; }
        public Nullable<int> QA_TECHNICIAN_ID { get; set; }
        public Nullable<int> QUALITY_ENG_ID { get; set; }
        public Nullable<System.DateTime> START_DATE { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
        public Nullable<System.DateTime> REGISTER_DATE { get; set; }
        public bool IS_ACTIVE { get; set; }
        public Nullable<int> MAP_SELECTION_ID { get; set; }
        public string MAKER { get; set; }
        public Nullable<System.DateTime> MAKER_DAT_TIM { get; set; }
    }
}
