//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RCVMM_ASSIGNED_LOV
    {
        public int ID { get; set; }
        public string ASSIGNED_TO_ENG { get; set; }
        public string ASSIGNED_TO_ARA { get; set; }
        public string SUCCESS_ASSIGN_TO { get; set; }
        public string REJECT_ASSIGN_TO { get; set; }
    }
}
