//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAMPLE
    {
        public int SAMPLE_ID { get; set; }
        public Nullable<int> CR_ID { get; set; }
        public string SAMPLE_MAKER { get; set; }
        public string SAMPLE_SIZE { get; set; }
        public string SAMPLE_LENGTH { get; set; }
        public Nullable<int> SAMPLE_UNIT_ID { get; set; }
        public Nullable<int> MAP_SELECTION_ID { get; set; }
    }
}
