//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEST_SPATIAL_DATA
    {
        public int COL_ID { get; set; }
        public string MY_TYPE { get; set; }
        public System.Data.Spatial.DbGeometry SHAPE { get; set; }
    }
}
