//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERS_PROFILE
    {
        public int PROFILE_ID { get; set; }
        public Nullable<int> USER_TYPE_ID { get; set; }
        public string NAME { get; set; }
        public Nullable<int> CONTACT_DETAILS_ID { get; set; }
        public Nullable<int> NATIONALITY_TYPE_ID { get; set; }
        public string NATIONAL_ID { get; set; }
        public string NATIONALITY_ID { get; set; }
        public string EMPLOYEE_ID { get; set; }
        public Nullable<int> SUPER_USER_ID { get; set; }
        public bool IS_PROJECTOWNER_MEMBER { get; set; }
        public Nullable<int> PROJECTOWNER_ID { get; set; }
        public string MAKER_ID { get; set; }
        public Nullable<System.DateTime> MAKER_DT_TIM { get; set; }
    }
}
