//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERS_LOGIN
    {
        public int PROFILE_ID { get; set; }
        public string USER_NAME { get; set; }
        public string HASHE_PASS { get; set; }
        public string SALT { get; set; }
        public Nullable<int> ROLE_ID { get; set; }
        public Nullable<System.DateTime> EXPIRY_DATE { get; set; }
        public bool IS_ACTIVE { get; set; }
        public bool RECORD_STAT { get; set; }
        public bool INITIAL_STAT { get; set; }
        public bool IS_LOCKED { get; set; }
    }
}
